### ISSUE TITLE
iOS control not returned back to application after successful login

### ISSUE THREAD

**Issue by vipulpatel9011** [Azure-Samples/active-directory-b2c-xamarin-native#102]
This is iOS specific issue. 

I have completed all the steps suggested in document over here https://azure.microsoft.com/en-in/resources/samples/active-directory-b2c-xamarin-native/

In Andtoid it is working fine. But in iOS it is not returning back to application after successful login.

Yes, Login page is displaying properly we can enter the credentials over there but once login in successful then browser is closed but debugger not attaching back to application.

I have Eneabled Keychain access, Added Url Types in info.plist and also added below code to AppDelegate.cs

 public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
        {
            AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(url);
            return true;
        }

And on FInishLaunching event I have added below code

var authenticationService = DependencyService.Get<IAuthenticationService>();
            // Default system browser
            authenticationService.SetParent(null);

Please let me know if I am missing something. Your help is much appreciated.

Thanks.

**Comment by jennyf19** [comment]
@vipulpatel9011 In Info.plist, do you have the following:
```CSharp
<key>CFBundleURLSchemes</key>
			<array>
				<string>msal{clientId}</string>
			</array>
```

**Comment by vipulpatel9011** [comment]
Hi @jennyf19 , Yes I have already added. Please find the attached image. I have also allowed keychain access.
![ios](https://user-images.githubusercontent.com/34236599/64935465-04805700-d86f-11e9-8be2-991501cec283.png)

**Comment by jennyf19** [comment]
@vipulpatel9011 Can you run the sample as-is and see if it works for you (without changing any of the settings)?

**Comment by vipulpatel9011** [comment]
Hi @jennyf19 ,

It is working fine with demo code. Am I missing something? I followed all the steps mentioned in the document.

Thanks,

**Comment by vipulpatel9011** [comment]
Hi @jennyf19 ,

Got the issue. Actually I am calling SignInAsync method from OnAppearing event of view. So after successful validation OnAppearing event is firing again and it lost the previous flow.

Can you please try with calling SignInAsync method from OnAppearing event of view?

Thanks for your help.

**Comment by vipulpatel9011** [comment]
Hi @jennyf19 , Is there any update? I don't want to add extra screen, so I am calling SignInAsync mehod from OnAppearing.

**Comment by jennyf19** [comment]
@vipulpatel9011 What code do you have in OnAppearing? You can check the GetAccounts and see if there are any accounts already available from a previous sign-in, but otherwise you will be getting prompted for each time OnAppearing is called (or a silent call will be made). Can you share your code or a repro?

**Comment by vipulpatel9011** [comment]
Hi @jennyf19, I have changed the demo code only. You can download demo code from below link.
https://drive.google.com/file/d/14ORmZ7FY41KaKF4XORPWxs5vkVP0TZXo/view?usp=sharing

Yes, I am getting popup each time. Can you please help me with how to check GetAccounts? In demo we are using .WithAccount while requesting token, but still I am getting popup.

Thanks,
Vipul

**Comment by jennyf19** [comment]
@vipulpatel9011 sure, i'll take a look..i  am at a customer event the next couple of days, so may or may not be able to get to this immediately, but will try.

**Comment by jennyf19** [comment]
@vipulpatel9011 I should be able to look at this next week. sorry for the delay. have had some high priority issues w/ADAL and MSAL to sort out.

**Comment by jennyf19** [comment]
@vipulpatel9011 Thanks for the repro. I had to do two things, first update to the latest version of msal (4.7.1) due to iOS 13 changes and add `.ConfigureAwait(false)` to all the async calls. I think you were hitting a threading issue by starting the call in `OnAppearing()` but not awaiting the auth calls.

ex:
`var userContext = await authenticationService.SignInAsync().ConfigureAwait(false);`

```@csharp
 public async Task<UserContext> SignInAsync()
        {
            UserContext newContext = null;
            try
            {
                // acquire token silent
                newContext = await AcquireToken().ConfigureAwait(false);
            }
            catch (MsalUiRequiredException ex)
            {
                // acquire token interactive
                newContext = await SignInInteractively().ConfigureAwait(false);
            }
            return newContext;
        }
```

**Comment by jennyf19** [comment]
@vipulpatel9011 closing as resolved. feel free to reopen or create another. thanks.
