### ISSUE TITLE
[Doubt] Login without login webpage in Xamarin

### ISSUE THREAD

**Issue by talk2stephan** [Azure-Samples/active-directory-b2c-xamarin-native#105]
Is there any way I can create a native login page and authenticate user and get the barer token without using Azure AD B2C OAUTH 2.0 web page?

Based on the business requirement, I am not suppose to use the login through internal / external browser. Is there anyway I can achieve this. If possible could you please share some samples / documentation?

**Comment by jennyf19** [comment]
@talk2stephan Do you want to login w/an embedded webview, and not the system browser? B2C allows you to customize the login experience. We can set you up with the right B2C people, if that would be helpful.

**Comment by talk2stephan** [comment]
That means I can create a native login page and perform Login with out browser right?

Could you please share any documentation or samples I can refer?

**Comment by stackunderflows** [comment]
I am also interested in this.

**Comment by jennyf19** [comment]
@talk2stephan @stackunderflows  in B2C, you can customize every element of the login page. this should be a place to [start](https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview)

**Comment by stackunderflows** [comment]
@jennyf19 Is it possible to use an in-app webview instead of redirecting the user out of app to the browser?

**Comment by jennyf19** [comment]
@stackunderflows that should work fine as well. just know that Google does not accept embedded webview for auth, so if you're using Google as an IdP, it won't work w/embedded webview. We have more [info here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#google-auth-and-embedded-webview)

**Comment by jennyf19** [comment]
@talk2stephan do the links provided answer your question?

**Comment by thekeviv** [comment]
If I may, I also wanted to ask this and I don't think the links provided still provide the correct answer. So, when we use this approach, it opens a web view and the user logs in through that web view. We don't want to use a web view but use the native entry and button controls to implement our own user interface (and not just customize that we view using html/css). I stumbled upon the ROPC method but that has its own limitations. Is there any other way?

**Comment by jennyf19** [comment]
@thekeviv The app has to [delegate the authentication](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-scenarios#desktop-and-mobile-app-sign-in-flow-with-azure-ad) to AAD B2C, so we need to show a webview, either via the embedded webview or the system browser. More on [web browsers](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-web-browsers#web-browsers-in-msalnet). 
For B2C, you can customize the [webview entirely](https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview).

Not sure if you saw this information on [ROPC with B2C and MSAL](https://github.com/azuread/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#resource-owner-password-credentials-ropc-with-b2c).

**Comment by thekeviv** [comment]
I did see the ROPC Page as I wrote in the comment but it has it's own limitations as the documentation mentions. The reason why I don't want to use a webview is because we have already built our login/signup interface natively and want to use that instead of using the webview.

**Comment by jennyf19** [comment]
@thekeviv If you want to learn more about B2C UI customization, I can get you in contact with the B2C PMs and they can see how to help. If that's useful, please send me an email: jeferrie@microsoft.com

**Comment by thekeviv** [comment]
Sent! Thank You!

**Comment by jennyf19** [comment]
@thekeviv did you get your questions answered? Can we close this issue?

**Comment by thekeviv** [comment]
@jennyf19 Thanks for following back. What they told is that azure b2c does have support for building native login UI's using the ROPC flow. The concern I had about Microsoft mentioning it to be an insecure method was also answered and said that it's as secure as the methods by AWS/Google cloud. It's just Microsoft making us aware of the potential downsides of this approach. According to me it should be closed, please ask @talk2stephan as well once

**Comment by jennyf19** [comment]
Thanks for the update @thekeviv appreciated.

@talk2stephan  i'm going to close the issue, but please reopen, or continue the conversation here if needed, or open a new one. thank you.
