### ISSUE TITLE
Problem on android when you have several apps that use B2C

### ISSUE THREAD

**Issue by ivanrlg** [Azure-Samples/active-directory-b2c-xamarin-native#109]
Hi, I'm relatively new to Xamarin / Azure.

The problem is that I am using the ADD / B2C authentication system in 3 different Xamarin applications on Android, and it happens when I try to log, after entering the credentials does not redirects me to the application that called it.

I have removed all the apps and I try with just one and it works fine, but if I have all 3 at the same time installed on the phone then it happens that it redirects me to any other than the one trying to log in.

Possibly a misplaced configuration.

Pd: In UWP that problem does not happen ...

I'm using the nuget: Microsoft.Identity.Client 4.7.

**Comment by jennyf19** [comment]
@ivanrlg thanks for opening the issue. Can you share any of your code? Would be nice to see how you are setting up the public client application, the android manifest, and the acquire token calls. 

Do you have a repro you can share as well?

**Comment by jennyf19** [comment]
@ivanrlg -> do you have a repro  you can share?

**Comment by jennyf19** [comment]
@ivanrlg do you have a repro you can share?

**Comment by ivanrlg** [comment]
Hi, thanks for contacting, unfortunately I do not have a repo at this time to reproduce, the lack of response and the rush to finish the first few days forced me to change the logging system to something more archaic but functional. Thank you very much for answering. We could close the case if necessary.

**Comment by jennyf19** [comment]
@ivanrlg ok...i will close for now, but if you come across it again, please reopen (and tag me) or open a new issue. thanks.

**Comment by jennyf19** [comment]
@ivanrlg I think I hit the same problem randomly today while testing. I had to update the manifest file for android
```csharp
	<application android:label="UserDetailsClient.Droid">
    <activity android:name="microsoft.identity.client.BrowserTabActivity"
              android:configChanges="orientation|screenSize">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msal{client_id}" android:host="auth" />
      </intent-filter>
    </activity>
	</application>
```

see the android:scheme...it has the clientId and matches what should be the redirectURI in the portal.

The redirect URI for mobile has this format:
```csharp
.WithRedirectUri($"msal{B2CConstants.ClientID}://auth");
```
Which matches the android:scheme and android:host above. This should resolve the issue.
