### ISSUE TITLE
Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found after package update.

### ISSUE THREAD

**Issue by zerog33k** [Azure-Samples/active-directory-b2c-xamarin-native#11]
I am unable to get this example to work on android if I update the Android nuget packages to the recent 25.3.1 version.

To recreate this issue just download the example and update the nuget packages. I need to get this to work with the recent version.

**Comment by danieldobalian** [comment]
Hi @zerog33k, does the test device you're using have Chrome installed on the device?  Android versions of 25+ have it by default, but you may have deleted it by mistake.  

We have some [steps of how to install Chrome](https://github.com/Azure-Samples/active-directory-general-docs/blob/master/AndroidEmulator.md) on the device if this is the case. 

If you do and are still experiencing this, can you go ahead and enable logging in MSAL and post the logs here? [Here's](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/90dca9e8a28102d7eb0d96d70e93350f5a0e095a/tests/dev%20apps/DesktopTestApp/MainForm.cs#L59) some code that shows how to configure the logger, let us know if you run into any issues.

**Comment by zerog33k** [comment]
This is running the Xamarin forms app in this example. I get the same error when I try to integrate the MSAL 1.1 preview library into our code. It works fine on the iOS side.

Here's what the log looks like with all of the MSAL log output. The last line is when the exception is thrown.

---------: MSAL 1.1.0.0 MSAL.Xamarin.Android 25 [05/24/2017 03:57:21 - 4102c2fa-e009-48b4-b681-26a5a2e806df] === Token Acquisition (SilentRequest) started:
	Authority:  https://login.microsoftonline.com/tfp/mytennet.com/sign_up_in_default/
	Scope: 
	ClientId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Cache Provided: True
---------: MSAL 1.1.0.0 MSAL.Xamarin.Android 25 [05/24/2017 03:57:21 - 4102c2fa-e009-48b4-b681-26a5a2e806df] 
=== Request Data ===
Authority Provided? - True
Client Id - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Scopes - 
Redirect Uri - msauth-cxxxxxxxxxxxxc://msal
Validate Authority? - True
LoginHint provided? - False
User provided? - False
Extra Query Params Keys (space separated) - 
Slice Parameters Keys(space separated) - 


---------: MSAL 1.1.0.0 MSAL.Xamarin.Android 25 [05/24/2017 03:57:23 - 60a8f154-9d74-40b9-8347-734da301b300] === Token Acquisition (InteractiveRequest) started:
	Authority: https://login.microsoftonline.com/tfp/mytennet.com/sign_up_in_default/
	Scope: 
	ClientId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Cache Provided: True
---------: MSAL 1.1.0.0 MSAL.Xamarin.Android 25 [05/24/2017 03:57:23 - 60a8f154-9d74-40b9-8347-734da301b300] 
=== Request Data ===
Authority Provided? - True
Client Id - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Scopes - 
Redirect Uri - msauth-cxxxxxxxxxxxxc://msal
Validate Authority? - True
LoginHint provided? - False
User provided? - False
Extra Query Params Keys (space separated) - 
Slice Parameters Keys(space separated) - 

---------: MSAL 1.1.0.0 MSAL.Xamarin.Android 25 [05/24/2017 03:57:23 - 60a8f154-9d74-40b9-8347-734da301b300] Additional scopes - ;UIBehavior - select_account

---------: MSAL 1.1.0.0 MSAL.Xamarin.Android 25 [05/24/2017 03:57:23 - 60a8f154-9d74-40b9-8347-734da301b300] Resolving authority endpoints... Already resolved? - False
---------: MSAL 1.1.0.0 MSAL.Xamarin.Android 25 [05/24/2017 03:57:23 - 60a8f154-9d74-40b9-8347-734da301b300] Is Authority tenantless? - False

[Mono] Assembly Ref addref Microsoft.Identity.Client[0x9bff4040] -> Xamarin.Android.Support.CustomTabs[0x9bff4940]: 2

**Comment by zerog33k** [comment]
For what it's worth, I was able to get around this issue by taking the 1.1-preview release code, updating the android packages, and manually building a nuget package.

**Comment by ppopadiyn** [comment]
I started getting the same error after upgrading from v23 to the latest v25. After rollback again to v23, it started working again. I will try also the suggested workaround for building against the latest packages.

**Comment by daspuru** [comment]
zerog33k, I tried to do your fix, but I was not able to upgrade packages in the 1.1-previw solution code, as I am using VS For mac I think. Can you send me your Nuget? d a s p u r u @ g m a i l (dot) com

**Comment by adamhockemeyer** [comment]
I just worked around this...basically you need to downgrade any xamarin.android support libraries from v25 to v23.  I was using a newer version of ACR.UserDialogs for example that required a newer version, so I needed to downgrade that package to and older version.

**Comment by daspuru** [comment]
@adamhockemeyer Yes I know, I am also using ACR.UserDialogs, what versions did you have to use? Another thing I remember I read in a thread was that if you download the source code of the NuGet library for the Microsoft.Identity NuGet, and you upgrade the Android.Support.* pakages to compile to NuGet, the library will work. 

The point is that I tried to do that in my VS for Mac and was not able to compile (I think because of the IDE). If you have VS for windows maybe you can try that, and if you got that to work, please send me the NuGet! :)

Greetings.

**Comment by adamhockemeyer** [comment]
I'm VS for Mac as well.

For ACR.UserDialogs I'm using 6.3.10

I had to end up getting rid of several of the support libraries that were added in with the newer version the userdialogs.  It's building and running well now (finally).

Here are my versions of support libraries (with several being removed in order to get it to build).
`  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.CustomTabs" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.Palette" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Build.Download" version="0.4.3" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.247" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms.Maps" version="2.3.4.247" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Base" version="29.0.0.1" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Basement" version="29.0.0.1" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Maps" version="29.0.0.1" targetFramework="monoandroid71" />`

Hope this helps.

**Comment by daspuru** [comment]
@adamhockemeyer Thanks a lot! I will try.

**Comment by daspuru** [comment]
Great, I finally made it work. Here is my packages (in project.json format as I am using .NET Standard):

`{
  "dependencies": {
    "Acr.UserDialogs": "6.3.10",
    "Autofac": "4.6.0",
    "ExifLib.PCL": "1.0.2-pre01",
    "Microsoft.Azure.Mobile": "0.13.0",
    "Microsoft.Azure.Mobile.Analytics": "0.13.0",
    "Microsoft.Azure.Mobile.Crashes": "0.13.0",
    "Microsoft.Identity.Client": "1.1.1-alpha0387",
    "Newtonsoft.Json": "10.0.3",
    "Plugin.CurrentActivity": "1.0.1",
    "Plugin.ImageResizer": "1.0.1-alpha",
    "Plugin.Permissions": "1.2.1",
    "sameerIOTApps.Plugin.SecureStorage": "1.2.2",
    "sqlite-net-pcl": "1.3.2",
    "System.Reactive.Linq": "4.0.0-preview00001",
    "Xam.Plugin.Media": "2.6.2",
    "Xam.Plugins.Messaging": "4.0.0",
    "Xamarin.Android.Support.Animated.Vector.Drawable": "25.3.1",
    "Xamarin.Android.Support.Compat": "24.2.1",
    "Xamarin.Android.Support.Core.UI": "24.2.1",
    "Xamarin.Android.Support.Core.Utils": "24.2.1",
    "Xamarin.Android.Support.CustomTabs": "23.3.0",
    "Xamarin.Android.Support.Design": "23.3.0",
    "Xamarin.Android.Support.Fragment": "24.2.1",
    "Xamarin.Android.Support.Media.Compat": "24.2.1",
    "Xamarin.Android.Support.Transition": "24.2.1",
    "Xamarin.Android.Support.v4": "24.2.1",
    "Xamarin.Android.Support.v7.AppCompat": "23.3.0",
    "Xamarin.Android.Support.v7.CardView": "23.3.0",
    "Xamarin.Android.Support.v7.MediaRouter": "23.3.0",
    "Xamarin.Android.Support.v7.Palette": "23.3.0",
    "Xamarin.Android.Support.v7.RecyclerView": "23.3.0",
    "Xamarin.Android.Support.Vector.Drawable": "23.3.0",
    "Xamarin.Build.Download": "0.4.5",
    "Xamarin.FFImageLoading.Forms": "2.2.10-pre-408",
    "Xamarin.Forms": "2.3.4.247",
    "Xamarin.GooglePlayServices.Location": "42.1024.0-beta1"
  },
  "frameworks": {
    "MonoAndroid,Version=v7.1": {}
  },
  "runtimes": {
    "win": {}
  }
}`

**Comment by daspuru** [comment]
I hope someone at Microsoft can tell us when will the upgrade to this issue be available, as other libraries depend a lot on Xamarin.Android.Support latest package versions.

I think this is critical.

Thanks.

**Comment by jhondev** [comment]
Same problem here

**Comment by parakhj** [comment]
I would recommend filing an issue in this [repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet). It will hopefully get prioritized/resolved in the next version

**Comment by Journeyman42** [comment]
Same issue

09-14 14:40:09.827 W/art     ( 4333): JNI RegisterNativeMethods: attempt to register 0 native methods for md54c4b48a882a4c6b363ccb67bdb21d5b2.CustomTabActivityHelper
09-14 14:40:09.901 D/Mono    ( 4333): Assembly Ref addref Authentication.Android[0xad031820] -> Microsoft.IdentityModel.Clients.ActiveDirectory.Platform[0xad031ac0]: 2
09-14 14:40:09.901 D/Mono    ( 4333): Assembly Ref addref Authentication.Android[0xad031820] -> PCLCrypto[0xad031d00]: 3
An unhandled exception occured.

09-14 14:40:20.949 D/Mono    ( 4333): DllImport attempting to load: '/system/lib/liblog.so'.
09-14 14:40:20.949 D/Mono    ( 4333): DllImport loaded library '/system/lib/liblog.so'.
09-14 14:40:20.949 D/Mono    ( 4333): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
09-14 14:40:20.949 D/Mono    ( 4333): Searching for '__android_log_print'.
09-14 14:40:20.949 D/Mono    ( 4333): Probing '__android_log_print'.
09-14 14:40:20.949 D/Mono    ( 4333): Found as '__android_log_print'.
09-14 14:40:20.955 I/MonoDroid( 4333): UNHANDLED EXCEPTION:
09-14 14:40:21.005 I/MonoDroid( 4333): System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.
09-14 14:40:21.005 I/MonoDroid( 4333):   at Xamarin.Auth._MobileServices.WebAuthenticatorNativeBrowserActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x000bb] in <67253dd203fd4f92b629995044af3ab3>:0 
09-14 14:40:21.005 I/MonoDroid( 4333):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <d278c06ad5684d6882c743a94a93ebc2>:0 
09-14 14:40:21.005 I/MonoDroid( 4333):   at (wrapper dynamic-method) System.Object:cbca8e7c-9b19-4f18-93d0-d17ba1de69e9 (intptr,intptr,intptr)
09-14 14:40:21.028 W/art     ( 4333): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
09-14 14:40:21.031 D/Mono    ( 4333): DllImport searching in: '__Internal' ('(null)').
09-14 14:40:21.031 D/Mono    ( 4333): Searching for 'java_interop_jnienv_throw'.
09-14 14:40:21.031 D/Mono    ( 4333): Probing 'java_interop_jnienv_throw'.
09-14 14:40:21.031 D/Mono    ( 4333): Found as 'java_interop_jnienv_throw'.

**Comment by SureshbabuLucky** [comment]
Hi,

Experiencing exception in Azure B2C Directory login by using MSAL Library on Android platform with the following two libraries when updated to latest version (26.1.0.1)

1. Xamarin.Android.Support.CustomTabs (version 26.1.0.1)
2. Xamarin.Android.Support.v4 (version 26.1.0.1)

Note: Updating above two packages in MSAL sample also getting following error

Please download sample from the following Link:

https://github.com/Azure-Samples/active-directory-b2c-android-native-msal

Exception:
System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

StackTrace:
MonoDroid( 7659): UNHANDLED EXCEPTION:
MonoDroid( 7659): System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.
MonoDroid( 7659):   at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] :0 
MonoDroid( 7659):   at (wrapper dynamic-method) S
An unhandled exception occured.

**Comment by josuuribe** [comment]
I solved it installing the alpha version

**Comment by SureshbabuLucky** [comment]
@josuuribe,

Thanks for suggestion.i am tried what you suggested thing but it's not working same exception will getting in android.

**Comment by Paul-Schroeder** [comment]
@adamhockemeyer thank-you for posting your solution.  Changing the target Android version from 24 to 23 was the final piece that got this working for me.

**Comment by Schinwinkwinsky** [comment]
@josuuribe what alpha version did you install? I´m trying to use MSAL with CustomTabs 26.1.0.1 and I still get the Unhandled Exception.

**Comment by RhomGit** [comment]
This is still an issue.
`12-04 14:59:35.800 I/MonoDroid( 7110): UNHANDLED EXCEPTION:`
`12-04 14:59:35.833 I/MonoDroid( 7110): System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.`
`12-04 14:59:35.833 I/MonoDroid( 7110):   at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <e975227ac8644a30bb0866117325de0d>:0 `
`12-04 14:59:35.833 I/MonoDroid( 7110):   at (wrapper dynamic-method) System.Object:ca22d140-50b4-48ab-9278-75f7104c8dbc (intptr,intptr)`

**Comment by bakebak** [comment]
Hey guis,
the Microsoft.Identity.Client 1.1.1-preview0040 was updated day 05/01/2018 
See: https://www.nuget.org/packages/Microsoft.Identity.Client/1.1.1-preview0040
Now works with all libraries in version 25+

**Comment by crgarcia12** [comment]
I still have the problem with the latest one: 1.4.1

**Comment by davidmn** [comment]
I have the same issue @crgarcia12

**Comment by jlucaspains** [comment]
@davidmn How did you downgrade CustomTabs? Did you downgrade all Support.* packages along?

**Comment by daspuru** [comment]
Use Microsoft.Identity.Client version 1.1.3-alpha0007 with Android support libraries V 27.0.2 and it should work. That version can be found in this Nuget feed: https://www.myget.org/F/aad-clients-nightly/api/v3/index.json

**Comment by jennyf19** [comment]
@daspuru @jlucaspains  @davidmn @crgarcia12 @bakebak @RhomGit 

Closing this, as we now have the option for [embedded webview](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#by-default-msalnet-supports-a-system-web-browser-on-xamarinios-and-xamarinandroid) in MSAL (which does not require custom tabs)...please check out the [MSALv2.0.1-preview release](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/MSAL-V2.0.1).


We would love your feedback as well. You can reach me directly or open an issue on the [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues). 
Thanks!
