### ISSUE TITLE
Can't switch users

### ISSUE THREAD

**Issue by stackunderflows** [Azure-Samples/active-directory-b2c-xamarin-native#110]
If you login as user A, log out, then try to login as user B, it automatically logs you in as user A again. The login information appears to be cached in the browser. How can I change users? Is there an option to not user the browser?

**Comment by jennyf19** [comment]
@stackunderflows are you using the sample as-is? Which platform (iOS/Android)?

**Comment by stackunderflows** [comment]
Using the app as-is. Same behavior on iOS and Android. I had this problem when using the Microsoft auth provider. On Android, if I clear the data from Chrome it will ask for a username again. So it's something with the browser caching the login info.

**Comment by jennyf19** [comment]
@stackunderflows I see, this is from the session cookies. You can try adding a prompt value on [this line](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.Core/Features/LogOn/B2CAuthenticationService.cs#L88)...something like:
`.WithPrompt(Prompt.SelectAccount)` -> this will force an account selection dialog w/all the accounts used previously and then you can select a new one

`.WithPrompt(Prompt.ForceLogin)` -> this will prompt for credentials always, even if not needed. 

More info on using [`.WithPrompt()`](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#withprompt)

**Comment by jennyf19** [comment]
@stackunderflows does the above solution work for you?

**Comment by stackunderflows** [comment]
> @stackunderflows does the above solution work for you?

That works. Thanks!

**Comment by jennyf19** [comment]
@stackunderflows awesome. Am going to close, but reopen or make another if you hit other issues.
