### ISSUE TITLE
Android Redirect URI Not Working

### ISSUE THREAD

**Issue by codenshare** [Azure-Samples/active-directory-b2c-xamarin-native#123]
Configured Android App on ADB2C, When I click on login, it opens the login page but after entering the username and password, it keep on sticking to the same page the call does not come back on the app. 

I have read all the existing threads but have not been able to solve this, please help.

Steps followed on Azure:

1. Copied the package name - 
com.xamarin.adb2cauthorization

2. Generated Key using the following command on my machine and pasted in Signature: 
keytool -exportcert -alias androiddebugkey -keystore ~/.local/share/Xamarin/Mono\ for\ Android/debug.keystore | "C:\Program Files\OpenSSL-Win64\bin\openssl" sha1 -binary | "C:\Program Files\OpenSSL-Win64\bin\openssl" base64

In the Code, changed the following in the sample - 

In App.XAML.cs, replaced WithDirectURI in the following method as the existing code does not match the redirect URI created by azure. Copy pasted the Redirect URI from Azure. If I let it the same as original then my login page does not open. Also commented WithIosKeychainSecurityGroup

AuthenticationClient = PublicClientApplicationBuilder.Create(Constants.ClientId)
//.WithIosKeychainSecurityGroup(Constants.IosKeychainSecurityGroups)     //Commented this as this for Android               
 .WithB2CAuthority(Constants.AuthoritySignin)
.WithRedirectUri("msauth://com.xamarin.adb2cauthorization/3ZLW%2FTAqPvR43Zh79ejFQDOdka8%3D")
//.WithRedirectUri($"msal{Constants.ClientId}://auth")
.Build();  //Commented this and used the above

Now when I click on login, it opens the login page but after entering the username and password, it keep on sticking to the same page the call does not come back on the app. 

Please help!

**Comment by TiagoBrenck** [comment]
Hi @codenshare, did you also update the `DataScheme` at [MsalActivity.cs](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.Droid/MsalActivity.cs)?

**Comment by codenshare** [comment]
Thanks Tiago for the hint. There is more to it 

Found, the code is not updated for newer changes 
To fix the issue

In AndroidManifest.xml  Update the new schema for android:scheme:

` <activity android:name="microsoft.identity.client.BrowserTabActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        **<data android:scheme="msauth"
              android:host="com.xamarin.adb2cauthorization"
              android:path="/3ZLW/TAqPvR43Zh79ejFQDOdka8=" />**
      </intent-filter>
    </activity>`

Here is the link to documentation - https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-android-considerations
