### ISSUE TITLE
iOS access Popup

### ISSUE THREAD

**Issue by vipulpatel808** [Azure-Samples/active-directory-b2c-xamarin-native#124]
After integrating Azure AD B2C with xamarin.forms, iOS is asking for confirmation to open web application. Please find the attached image. 

How can we avoid this popup message?

![image](https://user-images.githubusercontent.com/37298782/77909597-7edc5b80-7242-11ea-83c7-12d47ea252a5.png)

**Comment by jmprieur** [comment]
@vipulpatel808: no you cannot avoid it. It's the OS showing it.

**Comment by vipulpatel0911** [comment]
Hi @jmprieur ,

Thanks for your reply. One more question, If this popup is open and I minimize the application and resume it again, popup is getting closed. So user don't have any option to do at the time of resume.

Can you please let me know if this is the expected behavior?

Thanks,
Vipul

**Comment by jmprieur** [comment]
@trwalke @aiwangmicrosoft

**Comment by jennyf19** [comment]
@oldalton do you know if this behavior is excepted w/the iOS popup?
"Thanks for your reply. One more question, If this popup is open and I minimize the application and resume it again, popup is getting closed. So user don't have any option to do at the time of resume."

**Comment by oldalton** [comment]
@jennyf19  While this behavior is not expected, it is Apple's bug, and there's nothing MSAL can do about it. I've seen it reported before as well with MSAL Obj-C library.

**Comment by jennyf19** [comment]
Thanks for the quick response @oldalton 

@vipulpatel0911 closing as external to MSAL .NET. Let us know if you run into any other issues.
