### ISSUE TITLE
Android Specific Considerations in README does not match code in project

### ISSUE THREAD

**Issue by joemc3** [Azure-Samples/active-directory-b2c-xamarin-native#125]
The reference in the README section has two line changes (that are different than the code in the project) and no mention of using the ParentWindow LocatorService or the MaslActivity.cs.  This is particularly confusing to those new to AAD B2C and Xamarin.

**Comment by jmprieur** [comment]
@trwalke @aiwangmicrosoft can we please update the README.md (align as much as possible with the Xamarin AAD sample without broker, as B2C does not support broker)

**Comment by jennyf19** [comment]
@trwalke do you have an ETA on this? Thanks.

cc: @henrik-me @aiwangmicrosoft

**Comment by trwalke** [comment]
by end of week

**Comment by jennyf19** [comment]
@trwalke sweet. thanks!
