### ISSUE TITLE
Problems when using your own tenant

### ISSUE THREAD

**Issue by FSchmidNT** [Azure-Samples/active-directory-b2c-xamarin-native#129]
Hi, 

I'm trying to use my own tenant, but I'm stuck on step six. Which ClientId must be used here? I don't copy anything at step 2 either. 

Thanks in advance

**Comment by jmprieur** [comment]
Did you register your application?
See https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-register-applications?tabs=applications#register-a-mobilenative-application

**Comment by FSchmidNT** [comment]
Yes, the app is registered. I also changed all credentials except the one in step 6.

**Comment by FSchmidNT** [comment]
![image](https://user-images.githubusercontent.com/59088039/81189386-c9c25f00-8fb6-11ea-8782-27a79a98ce74.png)

I do not understand what ID is meant here. In step 2 (Get your own Azure AD B2C tenant) I do not get a ClientID?!

**Comment by TiagoBrenck** [comment]
The clientId is the application ID that you have registered. You can find it under **App Registration**>**Your App**>**Overview tab**:
![image](https://user-images.githubusercontent.com/16087102/81333122-f333c700-9058-11ea-87b8-9d7110909db6.png)

**Comment by FSchmidNT** [comment]
I figured out how it works. Thanks for the help

**Comment by jennyf19** [comment]
Thanks @FSchmidNT Please reopen or create another issue if you need more assistance.
