### ISSUE TITLE
System.TypeLoadException from UIParent on Android

### ISSUE THREAD

**Issue by cvanbeek13** [Azure-Samples/active-directory-b2c-xamarin-native#13]
I was using this code to setup my B2C code after updating to Microsoft.Identity.Client version 1.1.0 and ran into the following problem when I ran it on Android:

The code compiled and the Build completed but when I debugged it on my Galaxy S5, it crashed before making it to the MainActivity OnCreate() method.  Here is the exception it listed:

06-10 14:34:03.883 E/mono    (22353): Unhandled Exception:
06-10 14:34:03.883 E/mono    (22353): System.TypeLoadException: Could not load type of field 'MyApp.App:UiParent' (16) due to: Could not resolve type with token 0100008c (from typeref, class/assembly Microsoft.Identity.Client.UIParent, Microsoft.Identity.Client, Version=1.1.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae) assembly:Microsoft.Identity.Client, Version=1.1.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae type:Microsoft.Identity.Client.UIParent member:<none>
06-10 14:34:03.883 E/mono-rt (22353): [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'MyApp.App:UiParent' (16) due to: Could not resolve type with token 0100008c (from typeref, class/assembly Microsoft.Identity.Client.UIParent, Microsoft.Identity.Client, Version=1.1.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae) assembly:Microsoft.Identity.Client, Version=1.1.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae type:Microsoft.Identity.Client.UIParent member:<none>

Do you know how to get around this error, or what it is caused by?

**Comment by parakhj** [comment]
Does it crash after you click "Sign in"?

**Comment by cvanbeek13** [comment]
No, it crashes before the app is even started.  I'm using Xamarin.Forms PCL and starting the PCL app from the MainActivity of the Android App, but when I debugged it, it crashed before OnCreate() of the MainActivity was even started.

**Comment by parakhj** [comment]
@danieldobalian or @vibronet any advice?

**Comment by danieldobalian** [comment]
@cvanbeek13 looks like this may be a Xamarin issue as described here: https://developercommunity.visualstudio.com/content/problem/54624/could-not-load-type-of-field-xamarinformsdesignxam.html.  Can you try upgrading to the version the chat is talking about here and retry?

**Comment by cvanbeek13** [comment]
I had to uninstall and reinstall all my NuGet packages, they're back to the same versions now as they were before.  This error is stopped (gotta love Xamarin), but now it won't load the Android UI, so I'll be fidgeting with that for a while.  Thank you for the help!
