### ISSUE TITLE
Node.js Web API with Azure AD B2C

### ISSUE THREAD

**Issue by plettb** [Azure-Samples/active-directory-b2c-xamarin-native#132]
It's probably asking too much, but could this sample be built on a .NET back end instead of one in Node.js (see step 4 of the instructions)?  Alternatively, has anyone translated [this sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi) into a C# project?  This is a great sample and I want my application working exactly the same way, but I can't seem to get there with my own Web API, and the instructions being linked to are insufficient.

Thanks!
Brad.

**Comment by jennyf19** [comment]
@plettb Here is a c# [one](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C) which shows how to secure a web API built with ASP .NET Core. The sample has a client web app and calls a protected web API. This is the closest we have to a c# web API, as all of our samples use the same node .js one.

Let us know if this helps at all.

**Comment by plettb** [comment]
> @plettb Here is a c# [one](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C) which shows how to secure a web API built with ASP .NET Core. The sample has a client web app and calls a protected web API. This is the closest we have to a c# web API, as all of our samples use the same node .js one.
> 
> Let us know if this helps at all.

Having tinkered with that for a while, I still haven't made any progress.  What's irritating is that this _should_ be relatively easy.  I'm likely making some more rookie mistakes, but...

If/when I get this working, I'll be sure to add to the documentation or the wiki or even provide a working .NET version, but until then... I'll plug along in growing frustration.

**Comment by jennyf19** [comment]
@plettb since this is unrelated to this sample, can we close the issue?

**Comment by plettb** [comment]
Sure thing.
