### ISSUE TITLE
OnAppearing() Method not found in example Code

### ISSUE THREAD

**Issue by tobo77** [Azure-Samples/active-directory-b2c-xamarin-native#134]
Thank you very much for this example! I can not find the provided OnAppearing-method in the code. Can you guys please explain, how to check the sign-in state, when the dialog appears and if the user is not signed-in, how to redirect to the ad b2c login-page automatically? A reply is highly appreciated!
Thank for our work again!

Tobias

**Comment by jennyf19** [comment]
@tobo77 does the conversation in this [issue](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/102#issuecomment-562693209) help at all? if not, let us know.
