### ISSUE TITLE
[UWP] We can't connect to the service you need right now. Check your network connection or try this again later. 

### ISSUE THREAD

**Issue by amirvenus** [Azure-Samples/active-directory-b2c-xamarin-native#137]
Hi,

I have tried the sample on iOS and Android and they work beautifully fine however, we would love to have the same for our UWP target inside the Xamarin.Forms project. 

I keep on getting the error:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/5879559/90454797-253ed580-e0ec-11ea-9179-3237c325f6ce.png">

I have also tried the 'registry key' trick as well as setting the capabilities as prescribed on some forums and discussions:
```

  <Capabilities>
    <Capability Name="internetClient" />
    <uap:Capability Name="enterpriseAuthentication"/>
    <Capability Name="privateNetworkClientServer"/>
    <uap:Capability Name="sharedUserCertificates"/>
    <uap:Capability Name="userAccountInformation"/>
    <Capability Name="internetClientServer"/>
  </Capabilities>

```
But it's still the same..

Please advise

Thanks!

**Comment by jennyf19** [comment]
@amirvenus looks like the same issue in this [sample](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/152). can you get back the info @bgavrilMS asked for in the linked sample? Thanks. feel free to reopen.

**Comment by Rathish100** [comment]
Any update on this Issue? Any solution for this ?

**Comment by kyurkchyan** [comment]
We are having the same problem :(

**Comment by bgavrilMS** [comment]
@kyurkchyan - did you check https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-uwp-considerations ?
