### ISSUE TITLE
Android slow login redirection

### ISSUE THREAD

**Issue by sfrsebastian** [Azure-Samples/active-directory-b2c-xamarin-native#14]
The sample runs fine on an Android device. Is it normal that it takes quite a while (at least 15 seconds) to redirect the user to the login page?

**Comment by danieldobalian** [comment]
That's not normal.  Just to check, are you running the original sample code, or have you made some changes?

Can you enable logging and post the logs here?  That'll help see if the app is taking awhile to pop the system browser, or to actually load the page. 

To turn on full MSAL logging, you'll need to implement a little bit of code like [here (web app)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/dev/tests/dev%20apps/WebTestApp/WebApp/Controllers/HomeController.cs#L57)

**Comment by sfrsebastian** [comment]
I'm running the original code on an LgG5 with Android 6.0.1, the only change I made was changing the minimum android version down to api level 23. I found out by testing on another device, a Samsung Galaxy S7 with Android 6.0.1, that the loading takes around 5 seconds (way less than on the LgG5).

I also tried to implement the logging part from the example you sent, but looks like no MSAL logging is showing up. I will investigate further and let you know if something new shows up. For now, if it helps, these are the logs from the LgG5 right after clicking the sign in button and after the browser shows up. 

`[ViewRootImpl] ViewRoot's Touch Event : ACTION_DOWN
[ViewRootImpl] ViewRoot's Touch Event : ACTION_UP
[AudioManagerEx] AudioManagerEx created
[Mono] DllImport attempting to load: '__Internal'.
[Mono] DllImport loaded library '(null)'.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'monodroid_get_system_property'.
[Mono] Probing 'monodroid_get_system_property'.
[Mono] Found as 'monodroid_get_system_property'.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'monodroid_free'.
[Mono] Probing 'monodroid_free'.
[Mono] Found as 'monodroid_free'.
Thread started: <Thread Pool> #2
Thread started: <Thread Pool> #3
Thread started: <Thread Pool> #4
[Mono] [0x9188a930] worker starting
[Mono] [0x91786930] worker starting
Thread started: <Thread Pool> #5
[Mono] [0x9167e930] worker starting
Loaded assembly: System.Net.Http.dll [External]
[Mono] The request to load the assembly System.Net.Http v4.0.0.0 was remapped to v2.0.5.0
[Mono] Image addref System.Net.Http[0xb77e7310] -> System.Net.Http.dll[0xb802f398]: 2
[Mono] Prepared to set up assembly 'System.Net.Http' (System.Net.Http.dll)
[Mono] Assembly System.Net.Http[0xb77e7310] added to domain RootDomain, ref_count=1
[Mono] AOT: image 'System.Net.Http.dll.so' not found: dlopen failed: library "/data/app/UserDetailsClient.Droid-1/lib/arm/libaot-System.Net.Http.dll.so" not found
[Mono] AOT: image '/usr/local/lib/mono/aot-cache/arm/System.Net.Http.dll.so' not found: dlopen failed: library "/data/app/UserDetailsClient.Droid-1/lib/arm/libaot-System.Net.Http.dll.so" not found
[Mono] Config attempting to parse: 'System.Net.Http.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Net.Http/System.Net.Http.config'.
[Mono] Assembly Ref addref Microsoft.Identity.Client[0xb7879ba0] -> System.Net.Http[0xb77e7310]: 2
[Mono] Assembly Ref addref System.Net.Http[0xb77e7310] -> mscorlib[0xb77ecd00]: 40
[Mono] Assembly Ref addref System.Net.Http[0xb77e7310] -> System[0xb7b9f5e8]: 11
Thread started:  #6
[Mono] Image addref Mono.Security[0xb78e6e60] -> Mono.Security.dll[0xb84bd470]: 2
[Mono] Prepared to set up assembly 'Mono.Security' (Mono.Security.dll)
[Mono] Assembly Mono.Security[0xb78e6e60] added to domain RootDomain, ref_count=1
[Mono] AOT: image 'Mono.Security.dll.so' not found: dlopen failed: library "/data/app/UserDetailsClient.Droid-1/lib/arm/libaot-Mono.Security.dll.so" not found
[Mono] AOT: image '/usr/local/lib/mono/aot-cache/arm/Mono.Security.dll.so' not found: dlopen failed: library "/data/app/UserDetailsClient.Droid-1/lib/arm/libaot-Mono.Security.dll.so" not found
[Mono] Config attempting to parse: 'Mono.Security.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/Mono.Security/Mono.Security.config'.
[Mono] Assembly Ref addref System[0xb7b9f5e8] -> Mono.Security[0xb78e6e60]: 2
[Mono] Assembly Ref addref Mono.Security[0xb78e6e60] -> mscorlib[0xb77ecd00]: 41
Loaded assembly: Mono.Security.dll [External]
[Mono] Assembly Ref addref System.Net.Http[0xb77e7310] -> System.Core[0xb7a70098]: 9
[Mono] Assembly Ref addref Mono.Android[0xb780afb0] -> System[0xb7b9f5e8]: 12
[Mono] [0x9188a930] hill climbing, change max number of threads 8
`

And once the browser shows up

`[Mono] Assembly Ref addref Mono.Security[0xb78e6e60] -> System[0xb7b9f5e8]: 13
Thread started: <Thread Pool> #7
Thread started: <Thread Pool> #8
[Mono] [0x911de930] worker starting
Thread started: <Thread Pool> #9
Thread started: <Thread Pool> #10
[Mono] [0x910dd930] worker starting
[Mono] [0x90fdc930] worker starting
[Mono] Unloading image System.dll [0xb85f9f20].
[Mono] Image addref System[0xb85fcc48] -> System.dll[0xb7b9e998]: 5
[Mono] Config attempting to parse: 'System.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/System/System.config'.
[Mono] Unloading image System.dll [0xb85f9f20].
[Mono] Image addref System[0xb85fe418] -> System.dll[0xb7b9e998]: 6
[Mono] Config attempting to parse: 'System.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/System/System.config'.
[Mono] Unloading image System.dll [0xb8594890].
[Mono] Image addref System[0xb85feeb8] -> System.dll[0xb7b9e998]: 7
[Mono] Config attempting to parse: 'System.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/System/System.config'.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_is_assignable_from'.
[Mono] Probing 'java_interop_jnienv_is_assignable_from'.
[Mono] Found as 'java_interop_jnienv_is_assignable_from'.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_get_byte_array_region'.
[Mono] Probing 'java_interop_jnienv_get_byte_array_region'.
[Mono] Found as 'java_interop_jnienv_get_byte_array_region'.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_set_byte_array_region'.
[Mono] Probing 'java_interop_jnienv_set_byte_array_region'.
[Mono] Found as 'java_interop_jnienv_set_byte_array_region'.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_new_object_array'.
[Mono] Probing 'java_interop_jnienv_new_object_array'.
[Mono] Found as 'java_interop_jnienv_new_object_array'.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_set_object_array_element'.
[Mono] Probing 'java_interop_jnienv_set_object_array_element'.
[Mono] Found as 'java_interop_jnienv_set_object_array_element'.
[Mono] The request to load the assembly System.Core v4.0.0.0 was remapped to v2.0.5.0
[Mono] Unloading image System.Core.dll [0xb85f13d0].
[Mono] Image addref System.Core[0xb85f5458] -> System.Core.dll[0xb7a6e098]: 6
[Mono] Config attempting to parse: 'System.Core.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Core/System.Core.config'.
[Mono] The request to load the assembly System.Core v4.0.0.0 was remapped to v2.0.5.0
[Mono] Unloading image System.Core.dll [0xb85ea0e8].
[Mono] Image addref System.Core[0xb85ea700] -> System.Core.dll[0xb7a6e098]: 7
[Mono] Config attempting to parse: 'System.Core.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Core/System.Core.config'.
[Mono] Image addref System.Runtime.Serialization[0xb86ba450] -> System.Runtime.Serialization.dll[0xb868ef00]: 2
[Mono] Prepared to set up assembly 'System.Runtime.Serialization' (System.Runtime.Serialization.dll)
[Mono] Assembly System.Runtime.Serialization[0xb86ba450] added to domain RootDomain, ref_count=1
[Mono] AOT: image 'System.Runtime.Serialization.dll.so' not found: dlopen failed: library "/data/app/UserDetailsClient.Droid-1/lib/arm/libaot-System.Runtime.Serialization.dll.so" not found
[Mono] AOT: image '/usr/local/lib/mono/aot-cache/arm/System.Runtime.Serialization.dll.so' not found: dlopen failed: library "/data/app/UserDetailsClient.Droid-1/lib/arm/libaot-System.Runtime.Serialization.dll.so" not found
[Mono] Config attempting to parse: 'System.Runtime.Serialization.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Runtime.Serialization/System.Runtime.Serialization.config'.
[Mono] Assembly Ref addref Microsoft.Identity.Client[0xb7879ba0] -> System.Runtime.Serialization[0xb86ba450]: 2
[Mono] Assembly Ref addref System.Runtime.Serialization[0xb86ba450] -> mscorlib[0xb77ecd00]: 42
[Mono] Assembly Ref addref System.Runtime.Serialization[0xb86ba450] -> System.Xml[0xb7b452b0]: 4
Loaded assembly: System.Runtime.Serialization.dll [External]
[Mono] Image addref System.ServiceModel.Internals[0xb8736088] -> System.ServiceModel.Internals.dll[0xb8725ca0]: 2
[Mono] Prepared to set up assembly 'System.ServiceModel.Internals' (System.ServiceModel.Internals.dll)
[Mono] Assembly System.ServiceModel.Internals[0xb8736088] added to domain RootDomain, ref_count=1
[Mono] AOT: image 'System.ServiceModel.Internals.dll.so' not found: dlopen failed: library "/data/app/UserDetailsClient.Droid-1/lib/arm/libaot-System.ServiceModel.Internals.dll.so" not found
[Mono] AOT: image '/usr/local/lib/mono/aot-cache/arm/System.ServiceModel.Internals.dll.so' not found: dlopen failed: library "/data/app/UserDetailsClient.Droid-1/lib/arm/libaot-System.ServiceModel.Internals.dll.so" not found
[Mono] Config attempting to parse: 'System.ServiceModel.Internals.dll.config'.
[Mono] Config attempting to parse: '/usr/local/etc/mono/assemblies/System.ServiceModel.Internals/System.ServiceModel.Internals.config'.
[Mono] Assembly Ref addref System.Runtime.Serialization[0xb86ba450] -> System.ServiceModel.Internals[0xb8736088]: 2
[Mono] Assembly Ref addref System.ServiceModel.Internals[0xb8736088] -> mscorlib[0xb77ecd00]: 43
[Mono] Assembly Ref addref System.ServiceModel.Internals[0xb8736088] -> System.Xml[0xb7b452b0]: 5
[Mono] Assembly Ref addref System.Runtime.Serialization[0xb86ba450] -> System[0xb7b9f5e8]: 14
Loaded assembly: System.ServiceModel.Internals.dll [External]
[Mono] Assembly Ref addref System.ServiceModel.Internals[0xb8736088] -> System[0xb7b9f5e8]: 15
[Timeline] Timeline: Activity_launch_request id:UserDetailsClient.Droid time:217946989
[Mono] Assembly Ref addref Microsoft.Identity.Client[0xb7879ba0] -> Xamarin.Android.Support.CustomTabs[0xb77e6210]: 2
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_call_int_method'.
[Mono] Probing 'java_interop_jnienv_call_int_method'.
[Mono] Found as 'java_interop_jnienv_call_int_method'.
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_get_object_field'.
[Mono] Probing 'java_interop_jnienv_get_object_field'.
[Mono] Found as 'java_interop_jnienv_get_object_field'.
[PhoneWindow] notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@a3375f4
[Timeline] Timeline: Activity_idle id: android.os.BinderProxy@3ca071 time:217947249
[Mono] Assembly Ref addref Xamarin.Forms.Platform.Android[0xb77f6b60] -> System.Runtime.Serialization[0xb86ba450]: 3
[Mono] Assembly Ref addref Xamarin.Forms.Platform.Android[0xb77f6b60] -> System.Xml[0xb7b452b0]: 6
Thread finished: <Thread Pool> #10
[Mono] [0x90fdc930] worker finishing
Thread finished: <Thread Pool> #8
[Mono] [0x911de930] worker finishing
`

I'll attach them too if they are too hard to read.
[afterBrowser.txt](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/files/1076084/afterBrowser.txt)
[beforeBrowser.txt](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/files/1076085/beforeBrowser.txt)

**Comment by sfrsebastian** [comment]
I just did some more testing and found out that the issue is related to my ISP. I changed the connection to my mobile plan and everything worked well. Thanks for the help @danieldobalian!

**Comment by danieldobalian** [comment]
Great, glad to hear it.
