### ISSUE TITLE
How to Hide the title bar in Android - for Login page

### ISSUE THREAD

**Issue by kberawala** [Azure-Samples/active-directory-b2c-xamarin-native#145]
For a xamarin forms app, is it possible to hide the title bar "My App" as show in the screen shot ?
I am using .WithUseEmbeddedWebView(true)

Thanks

![image](https://user-images.githubusercontent.com/13636878/104797550-9228d980-580a-11eb-8481-2e1e161aa801.png)

**Comment by jmprieur** [comment]
@kberawala : no it's not possible.

**Comment by kberawala** [comment]
any alternative suggestion ?
