### ISSUE TITLE
Can't get authentication to work w/ my own B2C tenant

### ISSUE THREAD

**Issue by peacefulvibes** [Azure-Samples/active-directory-b2c-xamarin-native#147]
Hello - I have went through tutorial and just can't get the authentication to work w/ my own b2c tenant when clicking sign in on both iOS (Safari cannot open the page because the address in invalid) and Android (blank screen) when it calls IPublicClientApplication.AcquireTokenInteractive().  I must have something slightly off or misconfigured...?

For iOS - From the PublicClientApplicationBuilder logging, it's trying to go to this url:

https://mycompany.b2clogin.com/tfp/mycompany.onmicrosoft.com/b2c_1_results_mobile_app_staging/oauth2/v2.0/authorize?scope=user.read+openid+profile+offline_access&response_type=code&client_id=xxxxxxxx-yyyy-40c1-804e-13190d66ccc6&redirect_uri=msalxxxxxxxx-yyyy-40c1-804e-13190d66ccc6:%2F%2Fauth&client-request-id=ef26ee69-9f31-4b22-943b-3d497a54e580&x-client-SKU=MSAL.Xamarin.iOS&x-client-Ver=4.25.0.0&x-client-OS=14.4&x-client-DM=iPhone&prompt=select_account&code_challenge=DfZ3m6w1WX5hE4SfzlugJNMggJrAZY3H8t288cBybk8&code_challenge_method=S256&state=cf886b1c-3353-4b05-b300-bb6e1f040b672de723bb-634e-460f-bfc5-e79698061b48

but if I use this format (updated from https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview) it works

https://mycompany.b2clogin.com/mycompany.onmicrosoft.com/oauth2/v2.0/authorize?client_id=xxxxxxxx-yyyy-40c1-804e-13190d66ccc6&redirect_uri=https%3A%2F%2Fjwt.ms&response_mode=form_post&response_type=id_token&scope=openid&nonce=dummy&state=12345&p=B2C_1_results_mobile_app_staging

I don't understand why AcquireTokenInteractive() in code is putting the userflow name (B2C_1_results_mobile_app_staging) in the path part of the url while the other one puts it as querystring parameter for p...

I have the iOS Redirect URL set up in the app registration's authentication:

![image](https://user-images.githubusercontent.com/629163/107661522-33eeeb00-6c3e-11eb-821c-f3732b4d22db.png)

and here is the userflow:

![image](https://user-images.githubusercontent.com/629163/107661558-3e10e980-6c3e-11eb-842a-8739e7449c1f.png)

Here is my pinfo.list:
```
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>com.yourcompany.UserDetailsClient</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>msalxxxxxxxx-yyyy-40c1-804e-13190d66ccc6</string>
        </array>
    </dict>
</array>

```

thank you!

**Comment by jennyf19** [comment]
@peacefulvibes does the sample work as-is (ex. w/out your own b2c tenant, but with the tenant and app info provided in the sample)?

for android, make sure to [update the scheme](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml#L12) w/your clientid `msal{client_id}`.

what is your b2c tenant? did you try w/embedded webview? just to see if that makes a difference.

**Comment by peacefulvibes** [comment]
@jennyf19 thank you for the reply.  actually it was my configuration on the authentication settings on azure - I didn't have it checked.  Sheesh.  I knew it was something easy.   I was out in the weeds with having other redirect URIs in the Android and iOS sections ...

![image](https://user-images.githubusercontent.com/629163/108585826-792ab100-72ff-11eb-804b-ba172f5952fd.png)

**Comment by jennyf19** [comment]
@peacefulvibes yeah...the new UI is confusing, I agree. Will pass the feedback along to the right team. Glad you are unblocked.
