### ISSUE TITLE
Running the Android Project results in exception 

### ISSUE THREAD

**Issue by stemoor** [Azure-Samples/active-directory-b2c-xamarin-native#160]
Hi, 

I cloned the repo and tried running the android project without any modifications to the code. However, I get the following error:
![image](https://user-images.githubusercontent.com/26838556/125703332-ef793c42-34eb-4737-ad06-dab192aae8ad.png)
Any ideas?

**Comment by jmprieur** [comment]
Did you clone the repo in a folder close to the root of your hard drive, @stemoor ?
this might be due to windows path length limit?

**Comment by stemoor** [comment]
No I did not. I fixed it to be in C: and it worked. Thanks!!
