### ISSUE TITLE
Not clear as to the purpose of Scope parameter

### ISSUE THREAD

**Issue by TomWalkerCodes** [Azure-Samples/active-directory-b2c-xamarin-native#17]
There is no documentation or explanation in the demo sample as the purpose of the Scope parameter.  I'm not clear on where in Azure AAD B2C tenant this parameter gets assigned.  Right now I've set this to empty string and it passes through the validation.

**Comment by parakhj** [comment]
Tom - Scopes are used to acquire specific types of tokens (id tokens, access tokens, or refresh tokens)

> Scopes are a space-separated list of values. A single scope value indicates to Azure AD B2C both of the permissions that are being requested. The offline_access scope indicates that your app will need a refresh_token for long-lived access to resources. You can also use the openid scope to request an id_token from Azure AD B2C. 

To acquire access tokens, see [this](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens). 

[Reference for definition](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oauth-code)

**Comment by Jeremywhiteley** [comment]
This blog post was a big help for this as well.  

https://azure.microsoft.com/en-us/blog/azure-ad-b2c-access-tokens-now-in-public-preview/
