### ISSUE TITLE
UrL bar when logging in.   

### ISSUE THREAD

**Issue by Jeremywhiteley** [Azure-Samples/active-directory-b2c-xamarin-native#18]
When I login using a iOS simulator, it gives me a URL bar at the top.  Is it possible to remove this?

**Comment by parakhj** [comment]
That is a feature of the system browser in iOS. I do not believe it is possible, but worth double checking iOS documentation

**Comment by Jeremywhiteley** [comment]
This is a show stopper for us.   I know you can do this in a Cordova app when calling a web view.   But I can't find any code that is calling a web view.

**Comment by parakhj** [comment]
Adding @vibronet and @gsacavdm who may be able to point out the code.

Out of curiosity, what is it about the address bar that you dislike?

**Comment by gsacavdm** [comment]
Sorry, I'm not familiar with any mechanism to achieve this.

**Comment by Jeremywhiteley** [comment]
I don't want the users seeing a URL like that.   We should be able to hide it if we want to.  If you have a health app, a user could see that a security risk.   Also the other issue is one swipe and you can make the whole UI bigger.   All this can be controlled by adding code to the web view.  however the web view is created by the PublicClientApplication.AcquireTokenAsync method which comes from one of the nugget packages.   So if you exposed some config settings on this method, we could change it and fix it so a user can't make the UI bigger.   
<img width="456" alt="screenshot 2017-06-27 13 12 58" src="https://user-images.githubusercontent.com/1545134/27607923-6423a0e0-5b3a-11e7-9ddd-a56acdfadc57.png">

**Comment by parakhj** [comment]
We are working on an experience that hides Microsoft's name (uses a more generic name), and if you'd like, possibly even customize it to your own name. 

You can control the UI of the page by customizing the log in experience and making it more mobile friendly. If needed, you can call different policies so that you display a different experience for web vs. mobile. Not the most elegant dev experience, but we are working to improve it.

**Comment by Jeremywhiteley** [comment]
@parakhj This is awesome news!  I know another company that wants this as well!    Thank you!

**Comment by daspuru** [comment]
We are also using AD B2C for a new app here. We would love to enhance this views. One tutorial for using XAML views in Xamarin.Forms and sending values by http requests for running the policies would be great addition too.

Thanks.
