### ISSUE TITLE
Azure MSAL login issue

### ISSUE THREAD

**Issue by riturajpandey** [Azure-Samples/active-directory-b2c-xamarin-native#19]
Hello guys

I am trying to login using username and password, after signup but getting following error
**Microsoft.Identity.Client.MsalServiceException: Returned user identifier does not match the sent user identifier at Microsoft.Identity.Client.Internal.Requests.RequestBase.SaveTokenResponseToCache ()**
I am using MSAL for login. and when we try to login with facebook, it works perfectly.

Please check the screen shot

![0-cus-d3-f9e42b91d54eeaf0e440b634656ebc15](https://user-images.githubusercontent.com/5201635/27732243-fcf1db82-5dad-11e7-9aa7-0796594554a6.jpg)

**Comment by parakhj** [comment]
This happens when you send a login hint or User into the acquireToken call and then the end user signs in with a different account. Hard to give specific guidance, but you may want to use a different overload without the login hint or User object.

**Comment by riturajpandey** [comment]
Can you please suggest me what i need to do? should i do any setting in azure portal?

**Comment by parakhj** [comment]
It doesn't have anything to do with the azure portal - just how you are making the call in your code. Could you a send a snippet of the code?

Adding @danieldobalian for further comments.

**Comment by riturajpandey** [comment]
Hello
thanks for response

Here is my login code
 public async static Task<bool> Login()
        {
			try
			{
				var ar = await App.PCA.AcquireTokenAsync(App.Scopes, LoginService.GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn), App.UiParent);
				if (ar != null)
				{
					if (!string.IsNullOrEmpty(ar.IdToken))
					{
                        UserDialogs.Instance.ShowLoading("Loading...");
                        return true;
					}
                    return false;
				}
                return false;
			}
			catch (Exception ex)
			{
                return false;
			}
        }
And this is my required settings
public static string Tenant = "medb2c.onmicrosoft.com";
		public static string ClientID = "2de815cb-540c-4033-bcaf-ad33796916d3";
		public static string PolicySignUpSignIn = "b2c_1_susi";
		public static string PolicyEditProfile = "b2c_1_edit_profile";
		public static string PolicyResetPassword = "b2c_1_reset";

		public static string[] Scopes = { "https://medb2c.onmicrosoft.com/demoapi/read" };
		public static string ApiEndpoint = "https://b2capidev.azurewebsites.net/api/values";

		public static string AuthorityBase = $"https://login.microsoftonline.com/tfp/{Tenant}/";
		public static string Authority = $"{AuthorityBase}{PolicySignUpSignIn}";
		public static string AuthorityEditProfile = $"{AuthorityBase}{PolicyEditProfile}";
		public static string AuthorityPasswordReset = $"{AuthorityBase}{PolicyResetPassword}";
		public static UIParent UiParent = null;
Please check this

thanks

**Comment by riturajpandey** [comment]
Hello Pankaj
I found another thing, when i try to login with Signup or signin policy, in this case i can only login with facebook, but when i try to login only with signin policy in this case i can only login with username and password not using facebook.

Can you help me out in this issue?

thanks

**Comment by tausif127** [comment]
how do we set the value of UiParent? It getting null when I try AcquireTokenAsync.

**Comment by jennyf19** [comment]
@riturajpandey @tausif127 closing, as this is pretaining to an old version of MSAL and the issues addressed here have been resolved in v2+. Please reopen if necessary. Thank you!
