### ISSUE TITLE
After signing up once, cookies storing password and cannot signout and signin with different user

### ISSUE THREAD

**Issue by tnjyothi** [Azure-Samples/active-directory-b2c-xamarin-native#2]
1. Go to 
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native
download xamarin sample code ,configure policies and your tenant
2. Run the code
3. Click on signup signin
4. Signup with local account 
5. Click on signout
6. click on signup sign 
 
Actual: It should allow to signup/sign in with different user 
automatically signing in with signed up user crdentials
Video: \\scratch2\scratch\v-jytati\Android\5554_android 5_23_2016 2_25_07 PM.mp4

**Comment by dstrockis** [comment]
Fixed server side.
