### ISSUE TITLE
Redirect URI not working on Android

### ISSUE THREAD

**Issue by jhvanderven** [Azure-Samples/active-directory-b2c-xamarin-native#22]
Hi all,

I followed the procedure described in the readme. On iOS it works as expected, but on Android, I can provide my credentials but then I get "This site can't be reached", It shows the expected redirect url msal{appid}://auth/?state={very long token} ERR_UNKOWN_URL_SCHEME.

This is my manifest:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<uses-sdk android:minSdkVersion="15" />
	<application android:label="XXXXXX"></application>
  <activity android:name="com.microsoft.windowsazure.mobileservices.authentication.RedirectUrlActivity" >
    <intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.DEFAULT" />
      <category android:name="android.intent.category.BROWSABLE" />
      <data android:scheme="msal{appid}" android:host="auth" />
    </intent-filter>
  </activity>
</manifest>

```
I have replaced {appid} with the id of my native application, not that of the API application.

My MainActivity contains the overridden OnActivityResult from the sample.

Please advise.

**Comment by Ripper555** [comment]
@jhvanderven You post helped me realize I didn't update my manifest. I'm not sure if this is you problem but don't forget to add Custom Redirect URI in the properties on azure:

`msal{appid}://auth`

Replacing the appid obviously.

**Comment by pedramp20** [comment]
I have exactly the same problem. I have configured the projects according to the instruction and set the custom redirect uri on the portal. However, I get the same error as explained in the question.
@jhvanderven have you found any solution yet?

**Comment by josuuribe** [comment]
@jhvanderven be care about activity, review tag <activity> it's <activity android:name="microsoft.identity.client.BrowserTabActivity"> not   <activity android:name="com.microsoft.windowsazure.mobileservices.authentication.RedirectUrlActivity" >
Use same example as provided in repo and replace {appid}

**Comment by pedramp20** [comment]
@josuuribe My AndroidManifest.xml is almost identical to the one provided example in the repo and I still have the problem.

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-sdk android:minSdkVersion="24" />
  <application android:label="Xxx.Droid" android:theme="@style/MyTheme"></application>
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <application>
    <activity android:name="microsoft.identity.client.BrowserTabActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msalf5fa7aa5-e531-416a-bd16-5cf1935a506a" android:host="auth" />
      </intent-filter>
    </activity>
  </application>
</manifest>
`
The only difference is this line that when I remove it I get an exception
`  <application android:label="Xxx.Droid" android:theme="@style/MyTheme"></application>`

**Comment by josuuribe** [comment]
@pedramp20 
Try this as is changing appid, it works for me, also check that your redirect url is right in Azure.
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-sdk android:minSdkVersion="25" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <application>
    <activity android:name="microsoft.identity.client.BrowserTabActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msalappid" android:host="auth" />
      </intent-filter>
    </activity>
  </application>
</manifest>
```

**Comment by pedramp20** [comment]
@josuuribe 
My manifest is exactly like what you posted. I need to include the theme definition otherwise I get an exception as I explained and I need to set the min sdk version to 23.

Regarding the dependencies, first the latest Microsoft.Identity.Client package available is 1.1.0-preview. I am not sure, how you could have  1.1.1-alpha0393

I have also updated all other packages to latest version but the problem persisted. I also could not downgrade my Xamarin.Forms to 2.3.4.270, I am currently using 2.4.0.269-pre2

**Comment by josuuribe** [comment]
I suggest you download the example and change the values pointing to your azure settings (tenant, appid, etc...) using **UWP** **not Android**, the example works fine in that way, you should be able to authenticate and be sure Azure is right configured.

The alpha version is required if you want to use the last package versions to avoid a bug related to tabs in Android (it's posted here in some place), that's the reason is better start with UWP, it's the most simple and easy to make it works.

Maybe you need sdk version 23, but try to get first something that works and then start to update  your poject to your desire target.

I do not use theme version and it works that's the reason i suggest you start from a simple example (this one) because maybe you have a configuration problem in your project, it's normal when you have done a lot of changes, sometimes is better remove all and start again from scratch.

**Comment by pedramp20** [comment]
@josuuribe Thank you for your suggestion. I actually had tried it (Android) before and ended up wasting so much time fixing and debugging this code that eventually decided to start from scratch and integrate it in my project and spend time on my own project. It is such a shame that Microsoft and/or Xamarin haven't provided a working example and I am pretty sure many people have just given up because of this frustrating process and have found an alternative.

I cloned the repo again and replaced the values to point to my azure and this time used the UWP project, however, I could't even get to the login page and got "**we can't connect to the service you need right now. Check your network connection or try this again later**".

I also updated the Microsoft.Identity.Client package to 1.1.1-alpha0393 but I still faced the same issue.

**Comment by josuuribe** [comment]
@pedramp20  If the example works with the default values but not with your values you have a configuration problem in Azure or setting the right values in the example.

As a trick try to connect to Windows Store, if you can not access to it maybe you have a real connectivity problem (proxy, firewall,...) for example fiddler creates a proxy and produces that error.

**Comment by jhvanderven** [comment]
Thanks for looking into this. I have not found a solution yet. @josuuribe
<https://github.com/josuuribe>: in my case the code works for iOS. So I
think that rules out a config error in Azure.

**Comment by pedramp20** [comment]
@josuuribe I am behind a proxy but if the proxy was the issue, how come it works with the original values?
I also can access Windows Store with no problem. 
Regarding the azure configuration, I doubt that I have made a mistake, but I am wondering, if there is any tool that I can manually test my settings and eliminate possible code and/or package issues?

**Comment by pedramp20** [comment]
@jhvanderven Have you tried to modify your AndroidManifest.xml based on the example provided and see if it solves your problem?

**Comment by josuuribe** [comment]
@pedramp20  If you can use the provide example without errors but changing the values for your values it does not work it is an Azure configuration error, the example worked for me using UWP with my own values. Follow all steps carefully and/or try to disable proxy to be sure it's not a problem.

**Comment by josuuribe** [comment]
@pedramp20  First time i tested it i thought i did not create Web API neither key and it worked, you will need it later, do not try to make all steps and then test, test step-by-step.
Also i do not suggest use one or another i only say that both work.

**Comment by pedramp20** [comment]
Azure configuration is very unlikely to be the case. Since, I did another test and replaced my azure settings values in my project with the values of this example to point to fabrikamb2c tenant and I still got the same error message that this site cant be reached.

I should note that I am using .NET Standard Class Library rather than PCL and wondering if this could cause this issue?

**Comment by josuuribe** [comment]
if using the example provided with your Azure settings you can not access it's an Azure configuration problem and if with Azure settings provided it does not work in your project you have also configuration problems in your project.

I do not know id standard/pcl is the problem (i use standard), really what is happening xamarin it's bringing to front a webview with azure login.

**Comment by jeer65** [comment]
It's working for me, although I had some trouble in settings on the AuthorityBase because on the example says that users have to add the **Tenant** but it really, you have to set the **TenantID** see below

 public static string AuthorityBase = $"https://login.microsoftonline.com/tfp/{TenantID}/";
where tenant Id was in my case 49ab60be-5713-481d-b294-b8bbc0b29dc6
so I set as below
public static string AuthorityBase = $"https://login.microsoftonline.com/tfp/49ab60be-5713-481d-b294-b8bbc0b29dc6/";

Once I set the TenantID after everything is starting working as expected

**Comment by jhvanderven** [comment]
I switched back to PCL (instead of dot net standard), downgraded Xamarin Forms to 2.3.4.224 and then it finally started to work on Android. @jeer65 I am using Tenant and not the ID. My packages.config is not attached (because .config is not supported). So I'll paste the contents:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Azure.Mobile.Client" version="4.0.2" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Identity.Client" version="1.1.1-preview0040" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.NETCore.Targets" version="1.1.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Newtonsoft.Json" version="11.0.1-beta3" targetFramework="portable45-net45+win8+wpa81" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="portable45-net45+win8+wpa81" />
  <package id="PInvoke.BCrypt" version="0.3.2" targetFramework="portable45-net45+win8+wpa81" />
  <package id="PInvoke.Kernel32" version="0.3.2" targetFramework="portable45-net45+win8+wpa81" />
  <package id="PInvoke.NCrypt" version="0.3.2" targetFramework="portable45-net45+win8+wpa81" />
  <package id="PInvoke.Windows.Core" version="0.3.2" targetFramework="portable45-net45+win8+wpa81" />
  <package id="runtime.native.System" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Collections" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Globalization" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.IO" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Linq" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Net.Http" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Reflection" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Runtime" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Runtime.Serialization.Json" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Threading" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Validation" version="2.2.8" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Xamarin.Forms" version="2.3.4.224" targetFramework="portable45-net45+win8+wpa81" />
</packages>

```
@pedramp20 This is my manifest:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="auto">
  <uses-sdk android:minSdkVersion="21" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <application>
    <activity android:name="microsoft.identity.client.BrowserTabActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msal{ClientID}" android:host="auth" />
      </intent-filter>
    </activity>
  </application>
</manifest>

```
Thanks for all your help.

**Comment by jcampana** [comment]
Hi everybody, I need your help. I Implement a PCL project with versions of iOS and Android.
iOS works fine, but Android version, the app open the login with Microsoft, but when redirect, i have the next error:

**Java.Lang.RuntimeException**
Unable to instantiate activity ComponentInfo{com.myapp/com.microsoft.identity.client.BrowserTabActivity}: java.lang.ClassNotFoundException: Didn't find class "com.microsoft.identity.client.BrowserTabActivity" on path: DexPathList[[zip file "/data/app/com.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-1/lib/x86, /data/app/com.myapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]

I use a device with Chrome installed, and use the same AndroidManifest.xml that you post here.

Any suggestion please?

Thanks in advance!

**Comment by jennyf19** [comment]
@jcampana - Which version of [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases) are you using?

**Comment by jcampana** [comment]
@jennyf19 I am using the version 1.1.1-preview0040, and runs OK.

**Comment by jennyf19** [comment]
@jcampana - So are you having issues w/Android on MSAL?

**Comment by jennyf19** [comment]
@jhvanderven - Are you still having issues with this sample?

**Comment by himadrinath** [comment]
@jhvanderven  i am running Android 8.0 api 26 getting this

![screenshot_20180419-200547](https://user-images.githubusercontent.com/12247490/39001898-f4e6645a-4414-11e8-98dd-3578295a4fdd.png)

but in my UWP application working Fine

**Comment by jennyf19** [comment]
@himadrinath - just saw this....is Chrome installed on the device? chrome or chrome custom tabs is required for MSAL to launch the UI.

**Comment by jennyf19** [comment]
@himadrinath did you ever get this figured out? 
Closing the issue, but feel free to reopen if necessary.

**Comment by isurujayasighe** [comment]
I have the same issue with uploaded apk to play store. but same apk works manually install
