### ISSUE TITLE
Call API

### ISSUE THREAD

**Issue by allussa** [Azure-Samples/active-directory-b2c-xamarin-native#23]
Hello,
I downloaded the code, I have configured the example with the data of my B2C azure, I have created two applications into the b2c tenant: one of native and the other web api, I have followed all the instructions provided, and when I call the api, I get the error: {"Message":"Authorization has been denied for this request."}

The API be made with Asp.net

Can you help me, please?

Toni

**Comment by parakhj** [comment]
Please double check that you have published scopes and granted them properly. See: https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens

If that doesn't help, please send screenshots of your set up in the portal, and then call web request that you are making

**Comment by allussa** [comment]
Hello Parakhj,

I attach the configuration that I have of the Azure b2c:

Thanks,

[AD B2C - Configuration.pdf](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/files/1270527/AD.B2C.-.Configuration.pdf)

**Comment by parakhj** [comment]
Sorry for the late reply! Did you figure it out?

**Comment by allussa** [comment]
Thanks. I have not it solved.

**Comment by parakhj** [comment]
It looks good ... are you getting an access token successfully? And then are you passing that token when you make the call to the API?

**Comment by allussa** [comment]
Yes, The access token and id token is returned, but I don't know how to verify the access token manually. :-(

To call the API I use:

HttpClient client = new HttpClient();
HttpRequestMessage message = new HttpRequestMessage(HttpMethod.Get, App.ApiEndpoint);
message.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
HttpResponseMessage response = await client.SendAsync(message);
string responseString = await response.Content.ReadAsStringAsync();
if (response.IsSuccessStatusCode)
{
  lblApi.Text = $"Response from API {App.ApiEndpoint} | {responseString}";
}
else
{
 lblApi.Text = $"Error calling API {App.ApiEndpoint} | {responseString}";
}

And I also tested it with the chrome plugin Advanced REST Client.

I don't know if the problem is in the APP or in the webapplication. If I could verify that the token is correct, I could discard the part of the app.

Thanks.

**Comment by parakhj** [comment]
Pull out the access token and paste it into https://jwt.ms. Does the 'aud' claim match the client ID of your API?

**Comment by allussa** [comment]
Yes, It does.

**Comment by parakhj** [comment]
And do the scp claims match what your API is looking for in the code?

**Comment by allussa** [comment]
Yes, It does.
Web.config:

<add key="api:ReadScope" value="read" />
<add key="api:WriteScope" value="write" />

Token:
scp | write read

In portal.azure, do the app service "web-api" requieres a specific configuration refent a b2c in the authentication settings?

Thanks

**Comment by parakhj** [comment]
Hmm could you try turning that off? This is going to add additional authentication on top of the one that I assume you have added in your own code.

If you want to use authentication through that particular channel, then check out this [blog](https://blogs.msdn.microsoft.com/appserviceteam/2016/06/22/app-service-auth-and-azure-ad-b2c/)

**Comment by Ripper555** [comment]
@parakhj @allussa 
I'm having the same problem with my API ASP core 2. I have posted on: 
https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi/issues/9 

Please let me know if you have a fix or able to start on new asp core 2 project with B2C without a problem. Thanks.

**Comment by Arsophia** [comment]
In .NET Core 2.0 The settings are a little bit different than .NET Core 1.1, here are my working settings for the API:

In Startup.cs (ConfigureServices method)
`services.AddAuthentication(options =>
			{
				options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
			})
			.AddJwtBearer(options =>
				{
                    options.Authority = string.Format("https://login.microsoftonline.com/tfp/{0}/{1}/v2.0/",
                                                      Portable.Constants.Constants.Tenant, Portable.Constants.Constants.PolicySignUpSignIn);
                    options.Audience = Portable.Constants.Constants.ClientID;
					options.RequireHttpsMetadata = false;
                    options.Events = new JwtBearerEvents
                    {
                        OnAuthenticationFailed = AuthenticationFailed
                    };
				});`

In Configure method (before app.UseMvc();):
`app.UseAuthentication();`

**Comment by jennyf19** [comment]
@allussa @Ripper555 @Arsophia @jdhuntington 
Closing as seems to be resolved. Please reopen if necessary. Thank you!
