### ISSUE TITLE
AccessToken is null

### ISSUE THREAD

**Issue by josuuribe** [Azure-Samples/active-directory-b2c-xamarin-native#24]
Hi,

Following all steps i have created (i have not added any scope) all elements, i am able to log in and user is registered, but AccessToken property is always null, however IdToken has a value, i suppouse it's a configuration issue but i do not know where is it.

Some people tells about is also necessary configure application authentication/authorization in Azure  and set "Azure Active Directory" as provider, but i do knot now if it's really necessary because i do not see any special effect.

I do not know if it's possible provide Azure configuration example used for this application code, i really appreciate it.

Thanks,

**Comment by parakhj** [comment]
Check out this doc to get started: https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens

**Comment by josuuribe** [comment]
Thanks, i am going to take a look, in the meantime in README.md step 6 point 4 says:

_Find the assignment for public static string ClientID and replace the value with the Application ID from Step 2._

Is it Application ID from step 2? is it not Application Id from step 5?

Thanks,

**Comment by josuuribe** [comment]
Thanks for the link, it's very useful information, now it works but there are two mistakes in readme.md.

Step 4, point 4:

_(Optional) Once you're app is created, open the app's Published Scopes blade and add any extra scopes you want._

This is not optional, it's mandatory create a scope with "read" name (or any other name) and link between applications (your link explained it fine).

Step 6 point 4 says:

_Find the assignment for public static string ClientID and replace the value with the Application ID from Step 2._

The Application Id is the one created in step 5, not 2.

(Optional) About code:

I use the next url, that is the one suggested in the link.

https://{tenant}.onmicrosoft.com/{app}**/**read

but it's true that:

https://{tenant}.onmicrosoft.com/{app}**.**read

Seems also work in example code.

It's also possible web api and client can be combined in the same app and do not create two, but  i am not sure.

**Comment by gsacavdm** [comment]
Hey @josuuribe , your feedback is spot on. I've updated the readme (see https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/commit/076ed31f3af9c82cd131efcc97d32f1c4fe6cb57) as per your suggestions, though don't hesitate to submit your own PRs if you have any other suggestions or improvements.

**Comment by muhammetsahin** [comment]
Hi,

I cant work this project. I did everything but i didnt work. Access Token return null.

![image](https://user-images.githubusercontent.com/2045788/34433206-d72dab5e-ec8e-11e7-8acb-46387ac47adb.png)
![image](https://user-images.githubusercontent.com/2045788/34433220-e8349872-ec8e-11e7-8ebb-fc95bc3f8cbc.png)
![image](https://user-images.githubusercontent.com/2045788/34433234-fbe06e96-ec8e-11e7-998c-9b7649277297.png)
![image](https://user-images.githubusercontent.com/2045788/34433333-a85f5d76-ec8f-11e7-9ae2-a8239dd63b5e.png)

![image](https://user-images.githubusercontent.com/2045788/34433350-cc1b2f92-ec8f-11e7-9e36-455fcac15942.png)
