### ISSUE TITLE
How to define scope?

### ISSUE THREAD

**Issue by pedramp20** [Azure-Samples/active-directory-b2c-xamarin-native#26]
In the provided example, the following string is presented as the scope and used to acquire the token. However, nowhere in the code or read me is explained clearly how this uri is constructed or defined. 

public static string[] Scopes = { "https://fabrikamb2c.onmicrosoft.com/demoapi/demo.read" };

It is only mentioned in Step 4 that "You'll need your own API or at the very least, you'll need to register a Web API with Azure AD B2C so that you can define the scopes that your single page application will request access tokens for"

Does it mean that I have to create a web api to act as an identity provider or this step is optional?

**Comment by josuuribe** [comment]
For me it was the same, read this => https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/24

**Comment by pedramp20** [comment]
Thank you @josuuribe
