### ISSUE TITLE
How to specify custom URI for xamarin.forms mobile app for registration link

### ISSUE THREAD

**Issue by rajamaheshwarsingh** [Azure-Samples/active-directory-b2c-xamarin-native#29]
How to specify custom URI for xamarin.forms mobile app when the user clicks on Register link on Azure B2C directory in sign-in page provided by Azure B2C directory.

In Azure portal, created custom link with URI "MyApplicatin://register". The link is visible in Azure login page in mobile application, but clicking on that link nothing is happening in the mobile app.

**Comment by parakhj** [comment]
Sorry, could you add a few screenshots or code? Not fully sure what the issue is

**Comment by rajamaheshwarsingh** [comment]
<img width="261" alt="login" src="https://user-images.githubusercontent.com/17141206/31422861-5816b008-ae6e-11e7-9de5-ed7bf67121f8.png">

**Comment by rajamaheshwarsingh** [comment]
when the user clicks on "Sign up Now" link, the user should be redirected back to custom registration page in mobile app. Our project requirement is not to redirect the user to registration page give by AZURE B2C directory. Instead redirecting the user to custom registration page which is a xaml page (Xamarin.Forms).
