### ISSUE TITLE
Sample doesn't work on Android (Nougat)

### ISSUE THREAD

**Issue by punitganshani** [Azure-Samples/active-directory-b2c-xamarin-native#30]
Tried running the sample on Android Device as well as Genymotion emulator (Android 7.1, API 25) but when we click on SignIn button, the application just gives an `UnhandledException` with no details. 

Followed all the steps mentioned in 
`https://azure.microsoft.com/en-us/resources/samples/active-directory-b2c-xamarin-native/` and skipped all Optional steps.

The error occurs on 

```
AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn), App.UiParent);
```

Is there any known issue?

**Comment by josuuribe** [comment]
Take a look on Android output in VS, it's possible that you need to install alpha version due to a problem with CustomTabs.

**Comment by punitganshani** [comment]
Not sure of this one. The unhandled exception isn't caused by the code

**Comment by punitganshani** [comment]
Is this the right version https://www.nuget.org/packages/Xamarin.Android.Support.CustomTabs/26.1.0-beta1

**Comment by Schinwinkwinsky** [comment]
I couldn´t use MSAL with Custom Tabs 26.x. I just got success with Custom Tabs 23.3 that asks for Xamarin Forms 2.4.
