### ISSUE TITLE
System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

### ISSUE THREAD

**Issue by SureshbabuLucky** [Azure-Samples/active-directory-b2c-xamarin-native#32]
Hi,

Experiencing exception in Azure AD B2C login by using MSAL Library on Android platform with the following two libraries when updated to latest version (26.1.0.1)

1. Xamarin.Android.Support.CustomTabs (version 26.1.0.1)
2. Xamarin.Android.Support.v4 (version 26.1.0.1)

Please download sample from the following link:

https://github.com/Azure-Samples/active-directory-b2c-android-native-msal

>Exception:
>System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

StackTrace:
>MonoDroid( 7659): UNHANDLED EXCEPTION:
>MonoDroid( 7659): System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.
>MonoDroid( 7659):   at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] :0 
>MonoDroid( 7659):   at (wrapper dynamic-method) S
>An unhandled exception occured.

**Comment by josuuribe** [comment]
Take a look here => https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/11

**Comment by SureshbabuLucky** [comment]
@josuuribe, 

Thanks for the suggestion.

I have taken look into that thread. They are suggesting to downgrade the Xamarin.Android.Support.Customtabs package to version 23.3.0. But in my project i'm unable downgrade the package from 26.1.0.1 to 23.3.0 because of having lot of dependencies.

**Comment by josuuribe** [comment]
This is my package list (it works 100%)

```
{
  "dependencies": {
    "Microsoft.Identity.Client": "1.1.1-alpha0393",
    "NETStandard.Library": "2.0.0",
    "Xamarin.Android.Support.CustomTabs": "25.4.0.2",
    "Xamarin.Android.Support.v4": "25.4.0.2",
    "Xamarin.Android.Support.v7.AppCompat": "25.4.0.2",
    "Xamarin.Forms": "2.3.4.270"
  },
  "frameworks": {
    "MonoAndroid,Version=v7.1": {}
  },
  "runtimes": {
    "win": {}
  }
}
```

**Comment by SureshbabuLucky** [comment]
@josuuribe ,Thanks a lot. It's Worked

**Comment by bakebak** [comment]
Hey guys,
the Microsoft.Identity.Client 1.1.1-preview0040 was updated day 05/01/2018
See: https://www.nuget.org/packages/Microsoft.Identity.Client/1.1.1-preview0040
Now works with all libraries in version 25+
