### ISSUE TITLE
Acquire token returns acessToken, but User, IdToken is null

### ISSUE THREAD

**Issue by IvanZaporozhchenko** [Azure-Samples/active-directory-b2c-xamarin-native#33]
I follow the steps, but AcquireTokenAsync returns accessToken, but User and IdToken is null. Am I misconfigure something?

**Comment by josuuribe** [comment]
Try => https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/24

**Comment by IvanZaporozhchenko** [comment]
@josuuribe Thanks!
The root cause was putting WebApi and Native App into one Application. But it should be 2 different applications.
Also, I should grant access to the Native app for WebApi app.
Reading this one helps - https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens
