### ISSUE TITLE
GetUserByPolicy always returns null

### ISSUE THREAD

**Issue by Schinwinkwinsky** [Azure-Samples/active-directory-b2c-xamarin-native#36]
Debugging the project, I noticed that the method GetUserByPolicy always returns null when it's called by AcquireTokenSilentAsync or AcquireTokenAsync and the login page doesn't appear. That way, the AuthenticateResult is not set.
On AADB2C/WebAPI it was set AppId URI as "https://{Tenant}/api" and the scope as "read".
On the app, the SignUpSignInPolicy is "B2C_1_susi" and the scope is "https://{Tenant}/api/read.

**Comment by Schinwinkwinsky** [comment]
Sorry, guys! It was just an AADB2C not properly set!

**Comment by jennyf19** [comment]
Thanks for the update @Schinwinkwinsky
