### ISSUE TITLE
For XF Android Developers - AquireTokenAsync Unhandled Exception Resolved

### ISSUE THREAD

**Issue by Schinwinkwinsky** [Azure-Samples/active-directory-b2c-xamarin-native#37]
I was facing an error in the Android project with MSAL. The Ios and UWP projects performed correctly. The login page was shown and I was able to get the AADB2C authentication. But when I run Android, the application broke with an Unhandled Excpetion. I did a search and I found the solution. The versions of Nuget Packages!
MSAL needs Xamarin.Android.Support.CustomTabs v23.3. With newer versions, I faced the same error. So don't update it, and use the Xamarin Foms v2.4.x. My Android project targets the Oreo version, 26 and runs properly.

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CommonServiceLocator" version="1.3" targetFramework="monoandroid80" />
  <package id="Microsoft.CSharp" version="4.4.0" targetFramework="monoandroid80" />
  <package id="Microsoft.Identity.Client" version="1.1.0-preview" targetFramework="monoandroid80" />
  <package id="Microsoft.NETCore.Platforms" version="2.0.1" targetFramework="monoandroid80" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="NETStandard.Library" version="2.0.1" targetFramework="monoandroid80" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="monoandroid80" />
  <package id="Prism.Core" version="7.0.0.168-pre" targetFramework="monoandroid80" />
  <package id="Prism.Forms" version="7.0.0.168-pre" targetFramework="monoandroid80" />
  <package id="Prism.Unity.Forms" version="7.0.0.168-pre" targetFramework="monoandroid80" />
  <package id="System.AppContext" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Collections" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.ComponentModel.TypeConverter" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Console" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Globalization" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Linq" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Net.Http" version="4.3.3" targetFramework="monoandroid80" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Reflection" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Serialization.Formatters" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="monoandroid80" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="monoandroid80" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Threading" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="monoandroid80" />
  <package id="Unity" version="4.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="23.3.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.CustomTabs" version="23.3.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Design" version="23.3.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v4" version="23.3.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="23.3.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.CardView" version="23.3.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="23.3.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="23.3.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="23.3.0" targetFramework="monoandroid80" />
  <package id="Xamarin.Forms" version="2.4.0.91020" targetFramework="monoandroid80" />
</packages>`

**Comment by Schinwinkwinsky** [comment]
I tried to put the code this way:

` protected override async void OnAppearing()
        {
            UpdateSignInState(false);

            // Check to see if we have a User
            // in the cache already.

            try
            {
                AuthenticationResult ar = await App.PCA.AcquireTokenSilentAsync(App.Scopes, GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn), App.Authority, false);

                //UpdateUserInfo(ar);

                //UpdateSignInState(true);
            }
            catch (Exception ex)
            {
                // Uncomment for debugging purposes
                //await DisplayAlert($"Exception:", ex.ToString(), "Dismiss");

                AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn), App.UiParent);

                // Doesn't matter, we go in interactive mode
                //UpdateSignInState(false);
            }
        }`

But for some reason, it didn´t work on Android. Even if you put the AcquireTokenAsync on a method and calling it inside of the above catch, you´ll receive an MSALUriRequiredException.

**Comment by jennyf19** [comment]
@Schinwinkwinsky closing, as this has been resolved with later versions of MSAL v2+. If you're still having issues, please reopen. Thank you!
