### ISSUE TITLE
Can't install pacakge Microsoft.Identity.Client

### ISSUE THREAD

**Issue by BleyChen** [Azure-Samples/active-directory-b2c-xamarin-native#39]
When i use vs2017 to create a xamarin forms project use pcl template , and then use command "Install-Package Microsoft.Identity.Client -Version 1.1.0-preview" to  install package for pcl project ,it show error as following:

Executing nuget actions took 218.01 ms
Found package 'Microsoft.Identity.Client 1.1.0-preview' in 'D:\bley\MOP\MOP-Master\packages'.
Install failed. Rolling back...
Package 'Microsoft.Identity.Client.1.1.0-preview' does not exist in project 'MOP'
Executing nuget actions took 691.56 ms
Could not install package 'Microsoft.Identity.Client 1.1.0-preview'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Schinwinkwinsky** [comment]
I made a test and I got to install. Try to delete the PCL project and add a new one. If don´t work, try to review the installation options.

![esboco](https://user-images.githubusercontent.com/13337108/33433198-751f41ac-d5b9-11e7-9857-a079744bee40.png)

**Comment by jmprieur** [comment]
Did you check the "preview" checkbox in the NuGet package manager? 
MSAL is still in preview, and therefore does not appear in the list otherwise
