### ISSUE TITLE
Social IDPs giving error during login

### ISSUE THREAD

**Issue by dstrockis** [Azure-Samples/active-directory-b2c-xamarin-native#4]
Frequently, upon selecting a social IDP in this sample, the login will fail displaying a correlation ID and generic error message from AAD B2C.

This is due to an improper request being sent to the social IDP by Azure AD B2C.  We are investigating and will update here when possible.

For now the recommendation is to use local accounts to complete the sample.

**Comment by trinnguyen** [comment]
We are having this issue as well, usually having server_error on Facebook/LinkedIn Login but after few times try to AcquireToken again, it gives Success Result.

We are using Xamarin + MSLA.

Do you have an estimate for next update about this bug fixed? Thanks

**Comment by trinnguyen** [comment]
Hi @dstrockis , can you give us some updates on this issue?
We are now using MSAL .Net and Xamarin for authentication with Facebook and LinkedIn, having this issue many times. 

These is no update on MSAL .Net https://github.com/AzureAD/microsoft-authentication-library-for-dotnet these days, even on their dev branch, I tried and got this issue as well.

Please confirm that this issue happen on MSAL .Net only, or all other platforms (like native iOS since there is an example with ObjC Auth library, native Android, web app)? 

If only on MSAL .Net, I will move to make binding of iOS ObjC library (from example) android Android SDK, to make this feature works on Xamarin. Or if happen on AD B2C server, so should temporary choose another solution.

**Comment by jasonchester** [comment]
I would also like an update on this issue.

**Comment by Jeremywhiteley** [comment]
I would like and update on this issue as well,  we are using Facebook to login with Azure AD B2C

**Comment by gsacavdm** [comment]
Hey guys, can you share the error message (and correlation ID if applicable) that you're getting so that we can investigate from our side?

**Comment by gsacavdm** [comment]
I'm closing this issue as there has been a major update to the library and the sample. If anyone still encounters this, please share the error message and correlation ID so that we can investigate.

**Comment by usolanki** [comment]
> I'm closing this issue as there has been a major update to the library and the sample. If anyone still encounters this, please share the error message and correlation ID so that we can investigate.

Hi gsacavdm,

I am still having issue as i am getting generic error message for facebook login on my azure b2c.:

https://portal.endorsehub.com/#/error=server_error&error_description=AADB2C%3a+An+exception+has+occurred.%0d%0aCorrelation+ID%3a+dc323245-16c3-4f6c-98a8-5c072eb6d5fe%0d%0aTimestamp%3a+2018-10-05+07%3a53%3a49Z%0d%0a

**Comment by yoelhor** [comment]
OAuth2 makes 3 requests to following endpoints:
1) **authorization** - where user sign-in to Facebook, then Facebook returns the authorizations code. Looks like this part completed successfully
2) **token**, Azure AD B2C reads and exchange the authorization toke to access code - this step failed in your case
3) **User info** endpoint

In the second step, Facebook returns 400 HTTP bad request error message  An exception was caught when making a request to URL "https://graph.facebook.com/oauth/access_token" using method "Get". 

Please check your Facebook client secret configured in AAD B2C. Did you change anything relates to the Facebook-OAUTH technical profile? This technical profile configured in the base policy and override with some other configurations in the extension policy.

Try the [Azure AD B2C Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=AzureADB2CTools.aadb2c) and [set up Azure AD B2C VS Code extension trace log](https://github.com/yoelhor/aad-b2c-vs-code-extension/blob/master/src/help/app-insights.md).

Yoel
