### ISSUE TITLE
Error on a custom screen from Microsoft.Identity.Client using CustomTabs

### ISSUE THREAD

**Issue by jeer65** [Azure-Samples/active-directory-b2c-xamarin-native#41]
**Xamarin.Android Version: 8.0**

**Operating System & Version : Microsoft Windows [Version 10.0.14393]**

**Support Libraries Version : API Level 21 Lollipop**

Describe your Issue:

An application to connect to Azure using AD to B2C authentication, is using the Microsoft.Identity.Client, and the version that is working is Custom Tabs 23.3, but when I tried to install through Nudget Microsoft.Identity.Client, this installs version Custom Tabs 26.x.
And when I run the code, it throws the following error,

12-06 02:09:42.177 D/ViewRootImpl@ec13238MainActivity: MSG_WINDOW_FOCUS_CHANGED 0
12-06 02:09:42.181 D/InputMethodManager( 6553): HSI from window - flag : 0 Pid : 6553
12-06 02:09:42.225 V/ActivityThread( 6553): performLaunchActivity: mActivityCurrentConfig={0 1.0 themeSeq = 0 showBtnBg = 0 311mcc480mnc [en_US] ldltr sw360dp w360dp h668dp 480dpi nrml long port ?dc finger -keyb/v/h -nav/h mkbd/h desktop/d s.53}
12-06 02:09:42.251 D/Mono ( 6553): Assembly Ref addref Microsoft.Identity.Client[0xdcdc2e80] -> Xamarin.Android.Support.CustomTabs[0xdc48d560]: 2
12-06 02:09:42.270 D/Mono ( 6553): DllImport searching in: '__Internal' ('(null)').
12-06 02:09:42.270 D/Mono ( 6553): Searching for 'java_interop_jnienv_get_object_field'.
12-06 02:09:42.270 D/Mono ( 6553): Probing 'java_interop_jnienv_get_object_field'.
12-06 02:09:42.270 D/Mono ( 6553): Found as 'java_interop_jnienv_get_object_field'.
An unhandled exception occured.

Steps to Reproduce (with link to sample solution if possible):

Run this code
AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn), App.UiParent);

**Comment by NikolaiTsepalov** [comment]
I have a similar problem on VS MAC
After updating Xamarin.Android.Support.CustomTabs version="23.3.0 to 26.1, clicking on the "Sign In" button causes the 
"Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found." exception.

**Comment by NikolaiTsepalov** [comment]
Looks like dev branch already has a fix for it
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/490
Please release a new version io the Microsoft.Identity.Client and update this sample app, current 1.1.0.0 preview is 4 months old.

**Comment by Schinwinkwinsky** [comment]
@jeer65 You need to use Xamarin 2.4.x. The new Xamarin version (2.5) doesn't support CustomTabs 23.

**Comment by jennyf19** [comment]
@NikolaiTsepalov @jeer65 Closing this, as this issue has been fixed with later versions of MSAL. If you still run into problems, please open an issue in the [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues). Thanks
