### ISSUE TITLE
Email login (no identity provider) dont work in 1.1.0

### ISSUE THREAD

**Issue by olivierma** [Azure-Samples/active-directory-b2c-xamarin-native#42]
I have successfully implemented an email login, without any identity provider with the 1.0.304142221-alpha. I update to 1.1.0_preview and I cannot do it. When I try to log in with my test address (...@msn.com), it's seems to try to log in to the Microsoft identity service. As my password are not the same in Microsoft identity provider and in my own B2C service, it fails to log in.

**Comment by gsacavdm** [comment]
I'm assuming this is not related to the sample given that it's already using 1.1.0_preview, so there's nothing to upgrade. In general, you need to make sure you are correctly setting the authority.

See [App.cs#L25-L26](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient/App.cs#L25-L26)

    public static string AuthorityBase = $"https://login.microsoftonline.com/tfp/{Tenant}/";
    public static string Authority = $"{AuthorityBase}{PolicySignUpSignIn}";   

and [MainPage.xaml.xs#L31](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient/MainPage.xaml.cs#L31)

    AuthenticationResult ar = await App.PCA.AcquireTokenSilentAsync(App.Scopes, GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn), App.Authority, false);

If continue to have issues with your app (and are unrelated to this sample), post it as an issue in StackOverflow with the [[azure-ad-b2c]](https://stackoverflow.com/questions/tagged/azure-ad-b2c) tag

**Comment by jennyf19** [comment]
@olivierma Closing, as this is relating to an outdated version of MSAL, we are now on 2.7. If you are still having issues, please re-open. Thank you!
