### ISSUE TITLE
Xamarin.Android can not run without chrome

### ISSUE THREAD

**Issue by zhurongbo111** [Azure-Samples/active-directory-b2c-xamarin-native#43]
I  download the sample and change the configuration to myself, it works well in iOS and UWP. But it doesn't work in android. I know that  run this example , Custom Chrome Tabs is required in android device, so it chrome is required too. But it is not receptive that ask my end users to install the chrome before using my app.I want to say that this library very fits our needs, but now I have to discard this library, and look for a new library. 

So is there any plan to remove the reliance on Custom Chrome Tabs?  
If I missed anything or there is any workaround, please let me know.

Thank you in advance.

**Comment by danieldobalian** [comment]
Yes, the plan is for MSAL to support more browsers than Chrome (and Chrome Custom tabs) before GA.

**Comment by jmprieur** [comment]
@parakhj : this is expected (even if not desirable). we might want to have a note in the Readme to explain that Android phone without chrome custom tabs won't be able to run the app leveraging MSAL.
We are currently working on adding embedded web browsers in MSAL, BTW to solve this issue.
