### ISSUE TITLE
active-directory-b2c-xamarin-native is broken

### ISSUE THREAD

**Issue by markti** [Azure-Samples/active-directory-b2c-xamarin-native#46]
The sample works but when I try to re-create it is impossible to re-create even with portable class library.

**Comment by jennyf19** [comment]
@markti What exactly are you having issues with when re-creating the sample? Are you following the directions from the ReadMe? If so, I can try to do the same and see if our issues match up.

**Comment by jennyf19** [comment]
@markti Which error messages are you getting when recreating the sample?

**Comment by jennyf19** [comment]
@markti Closing...as we haven't heard from you. Please reopen if you find issues and tag me. :)
