### ISSUE TITLE
Errors when authenticating

### ISSUE THREAD

**Issue by WilliamWatterson86** [Azure-Samples/active-directory-b2c-xamarin-native#54]
I have a Xamarin Forms app using the package and in general it works really well.  I am able to login and get a token that I am able to use for access to my web api etc.

Before each call to the API I am doing the following to authenticate silently.

`AuthenticationResult ar = await App.AuthenticationClient.AcquireTokenSilentAsync(ApplicationSettings.Scopes, Authentication.GetUserByPolicy(App.AuthenticationClient.Users, ApplicationSettings.PolicySignUpSignIn), ApplicationSettings.Authority, forceRefreshToken);

                if (ar != null)
                {
                    using (HttpClient client = new HttpClient(new NativeMessageHandler() { Timeout = TimeSpan.FromMilliseconds(30000) }))
                    {...}}` 

This works most of the time, but sometimes I am getting exceptions like this:

**Value cannot be null. Parameter name: key**
and 
**An item with the same key has already been added. Key: Accept**
and 
**An item with the same key has already been added. Key: User-Agent** 

This happens on every call until my app is restarted and then it all starts working again.

Is this just that the token has expired or something? Should I be asking the user to login again if any of these exceptions come back?

The version I am using in my app is: 1.1.1-preview0040

Thanks,

**Comment by jennyf19** [comment]
@WilliamWatterson86 Closing, as we have updated the sample to msal 2.7, and I believe the issues you are running into with the cache have been addressed. If you're still having issues, please reopen. Thank you!
