### ISSUE TITLE
Issue logging in with Twitter

### ISSUE THREAD

**Issue by andrewchungxam** [Azure-Samples/active-directory-b2c-xamarin-native#56]
Hello.  

Ran the project without modification to Visual Studio 2017 for Mac on iOS simulator: iPhone X iOS 11.4.

All the logins worked with the exception of the Twitter login.
(This is after pressing the Twitter login button -- but with no opportunity to type in a username/pass)

It created an error message that displayed as:
Sorry, but we're having trouble signing you in. 
We track these error automatically, but if the problem 
persists feel free to contact us.
In the meantime, please try again.

Correlation ID: b52514e3-1f88-4d87-b3b7-0cfb590e188d
Timestamp: 2018-07-02 20:43:28Z
AADB2C: An exceptions has occurred.

Is this something you have seen before?

**Comment by andrewchungxam** [comment]
![image](https://user-images.githubusercontent.com/3628580/42186053-fe5c2bf8-7dff-11e8-85c7-c3e3fcd0800f.png)

**Comment by parakhj** [comment]
What's your reply URL that you set in Twitter?

**Comment by jennyf19** [comment]
@parakhj - I get the same error message with Twitter login with the sample. Is it configured to work with Twitter login? Thanks!

**Comment by andrewchungxam** [comment]
Hi @parakhj thanks for your reply. (I didn't set any reply - I simply ran the sample in simulator.)

**Comment by andrewchungxam** [comment]
I saw this and I wonder if this is the issue:
https://codemilltech.com/quick-fix-your-azure-ad-b2c-twitter-settings/

**Comment by jennyf19** [comment]
Closing...this has been addressed.
