### ISSUE TITLE
Object Reference not set to an instance of an object Exception on iOS emulator

### ISSUE THREAD

**Issue by jotprabh1** [Azure-Samples/active-directory-b2c-xamarin-native#62]
I got the above exception on iOS with your sample. The problem that I figured out was that App.UiParent was not set. I solved it by adding App.UiParent = new UIParent() in the AppDelegate.cs after LoadApplication(). Please add the same to the sample.

**Comment by jennyf19** [comment]
@jotprabh1 The sample should be working out of the box now. Thank you. Closing this issue.
