### ISSUE TITLE
ApiEndpoint confusion/ check

### ISSUE THREAD

**Issue by upskydownshoes** [Azure-Samples/active-directory-b2c-xamarin-native#65]
Hi, just a quickie: what do I use as the ApiEndpoint, in your case: 

> https://fabrikamb2chello.azurewebsites.net/hello

I have followed all your steps: I have the B2C Tenant in the Azure Directory that holds my subscription (lets call it ADD1), I have the Applications and policies in a second directory (lets call it ADD2),.

in ADD1 I have added an App Service with the URL https://add1appservice.azurewebsites.net.

I have added this https://add1appservice.azurewebsites.net as the ApiEndPoint, but am getting a 401 error when clicking on "Call API" in the iOS app.

I can create users, login, signout fine however...

I should also point out that your sample worked great out of the box using https://fabrikamb2chello.azurewebsites.net/hello.

Many thanks.

**Comment by ClintFrancis** [comment]
In your app service instance, did you modify the params in the `index.js` file before uploading it?

```
// TODO: Update the first 3 variables
var tenantID = "[TenantID].onmicrosoft.com";
var clientID = "[ADB2C Web App ID]"; 
var policyName = "[Signup / Signin Policy Name]";```

**Comment by jennyf19** [comment]
@upskydownshoes did you get this figured out?

**Comment by jennyf19** [comment]
@upskydownshoes going to close, but please reopen if the issue persists. thanks.
