### ISSUE TITLE
Issues logging in with iOS

### ISSUE THREAD

**Issue by DominicBurford** [Azure-Samples/active-directory-b2c-xamarin-native#67]
We have implemented our login to use Azure AD B2C as per this example. It works perfectly fine with Android but we're having some weird issues with iOS.

When the user first launches the app, they are presented with the Azure AD B2C login form. They enter their credentials but are immediately redirected back to the login page again with the email address / passwords fields empty. After a few seconds they are eventually logged in. When they subsequently launch the app, they have to enter their credentials again (which they shouldn't have to - they should be automatically logged in).

We have tried this on several different iOS devices and they all display the same problem. We're using VS2017 v15.8.9 if that makes any difference. The devices are running versions 11.0, 12.0, 12.01 and 12.1 of iOS.

**Comment by DominicBurford** [comment]
Hi Jenny thanks for the response. After some investigation, the problem seems to be related to the Entitlements.plist file, as i have seen several similar posts on Stackoverflow where this this was the problem. I have updated this in exact accordance with the steps listed here on this example but no joy. 

We are using B2C local accounts only. The issue is with iOS only, Android is absolutely fine so the issue seems to be specific to iOS. We are using MSAL 2.1. I have tried to upgrade to 2.6.2 as suggested but we are now getting a completely different error when trying to create an instance of the MSAL client.

return AuthenticationService._pca ?? (AuthenticationService._pca =
                       new PublicClientApplication(ApplicationConstants.ClientId, ApplicationConstants.Authority)
                       {
                           RedirectUri = ApplicationConstants.CustomRedirectUrl
                       });

Has this changed between v2.1 and v2.6.2 in somwe way? The error I am now getting is:

System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)  at Microsoft.Identity.Client.Instance.Authority.CreateAuthority

**Comment by jennyf19** [comment]
@DominicBurford I was unable to repro the error using this sample and moving from 2.1 to 2.6.2. 
>System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions) at Microsoft.Identity.Client.Instance.Authority.CreateAuthority

Do you get the error with iOS and Android or just with iOS?
What authority are you passing in? 
Can you send [logs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#sample-for-logging-in-msal-2x) using 2.6.2? 

Let's work off of 2.6.2 and get things resolved for you there. We have had major cache fixes and improvements between 2.1 and 2.6.2. Let's get this new error resolved and then go from there.

Here is more [info](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-ios-specificities#enable-keychain-groups) on getting the Entitlements and keychain access set up with iOS. Please make sure you have the Entitlements.plist set correctly and have enabled keychain access. thank you.

**Comment by jennyf19** [comment]
@DominicBurford any update on this?

**Comment by DominicBurford** [comment]
Sorry been on annual leave. 

When I have upgraded MSAL to use 2.6.2 I get the exception

System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions) at Microsoft.Identity.Client.Instance.Authority.CreateAuthority

This is for both Android and iOS. The exception seems to suggest that MSAL is attempting to invoke a method that it can no longer find (deleted / renamed). We are using .NetStandard 2.0.3. Is this version compatible with MSAL 2.6.2?

**Comment by jennyf19** [comment]
@DominicBurford Thanks for the additional information. You will need to update to the latest Visual Studio version, for both VS for Mac and VS for Windows. There are many missing methods  (String.TrimStart, TrimEnd and Split). It is a Xamarin bug, but updating to latest VS has solved the issue for other customers. Can you try that and let me know if that fixes the issue for you?

**Comment by DominicBurford** [comment]
The latest version of Visual Studio is 2017 15.9.4 so I will upgrade to that today and re-test and let you know how I get on.

**Comment by jennyf19** [comment]
@DominicBurford Great! Thanks for the quick update. Glad to hear it is working. If you run into any more issues, please reach out, either via email (jeferrie@microsoft.com) or open an issue directly in [MSAL](https://github.com/azuread/microsoft-authentication-library-for-dotnet/issues)

Closing the issue.
