### ISSUE TITLE
Sample doesn't work properly on the iOS emulator

### ISSUE THREAD

**Issue by SaeedAkhter-MSFT** [Azure-Samples/active-directory-b2c-xamarin-native#7]
While the this sample runs fine in an actual iOS device, it does not work properly on the iOS emulator.
We are investigating and will update the sample if necessary.

**Comment by narindermakin** [comment]
It seems that App.PCA.Users count remains 0 after the call to the App.PCA.AcquireTokenAsync. It is not getting stored  after successful token response.

**Comment by jennyf19** [comment]
@narindermakin - Can you try w/the latest version of MSAL -> 3.0.8. ? thank you.

**Comment by narindermakin** [comment]
Well, we gave up on msal and Azure AD B2C after spending a good amount of time to solve issues.
    On Friday, May 3, 2019, 2:49:49 PM PDT, jennyf19 <notifications@github.com> wrote:  
 
 
@narindermakin - Can you try w/the latest version of MSAL -> 3.0.8. ? thank you.

**Comment by norton287** [comment]
This still does not work still with trying it with MSAL 4 release.  Works fine on my iPad mini but the simulator crashes.
