### ISSUE TITLE
AuthenticationFailed: IDX10214: Audience validation failed. Audiences: 

### ISSUE THREAD

**Issue by markti** [Azure-Samples/active-directory-b2c-xamarin-native#73]
I am trying to setup a xamarin app to talk to my WebAPI secured with AAD B2C authentication.

**Comment by markti** [comment]
https://nicolgit.github.io/cross-micro-services-authentication-Azure-B2C/

this fixed it. needed to add TokenValidationParameters to allow the application ID of my xamarin app. This is missing from your documentation!

![image](https://user-images.githubusercontent.com/3155241/51575250-72f74b80-1e7f-11e9-8d80-36bc17db1fb4.png)

**Comment by jennyf19** [comment]
@parakhj @jmprieur fyi on @markti 's comment about updating docs.

**Comment by jmprieur** [comment]
@markti where is the code for the Web API?
This cannot be right that the Web API accepts a token which is for your Web App. It shoud only accept a token for itself, but your mobile app needs to request a scope for the Web API.

cc: @parakhj  @jennyf19

**Comment by jennyf19** [comment]
@markti any update on this?

**Comment by jennyf19** [comment]
@markti - update?

**Comment by markti** [comment]
> @markti where is the code for the Web API?
> This cannot be right that the Web API accepts a token which is for your Web App. It shoud only accept a token for itself, but your mobile app needs to request a scope for the Web API.
> 
> cc: @parakhj @jennyf19

I dunno man. It works like this. Maybe my scopes are borked?

**Comment by markti** [comment]
![image](https://user-images.githubusercontent.com/3155241/57825238-feb52080-776b-11e9-898e-8ddb2328d69b.png)

here are my 3 app registrations in Azure AD B2C...

![image](https://user-images.githubusercontent.com/3155241/57825265-15f40e00-776c-11e9-8c80-9673debbd5b6.png)

Mobile app has access to the WebAPI using the permitted scopes defined here...

![image](https://user-images.githubusercontent.com/3155241/57825289-30c68280-776c-11e9-8db0-1f3939b30ba5.png)

scopes defined here in the WebAPI app definition

![image](https://user-images.githubusercontent.com/3155241/57825317-53589b80-776c-11e9-9a37-4d6a7fe2616d.png)

mobile app using B2C PublicClientApplicationBuilder
![image](https://user-images.githubusercontent.com/3155241/57825354-81d67680-776c-11e9-9826-fbe28d14dede.png)

mobile app uses one of the scopes defined in WebAPI and granted to mobile app...
![image](https://user-images.githubusercontent.com/3155241/57825399-bcd8aa00-776c-11e9-950a-85aebe205dec.png)

acquire token with the proper scope being passed in...
![image](https://user-images.githubusercontent.com/3155241/57825425-dc6fd280-776c-11e9-9cd6-0705a0d69628.png)

now server side in the webAPI...

appsettings uses the WebAPI application id
![image](https://user-images.githubusercontent.com/3155241/57825465-04f7cc80-776d-11e9-8d6b-574fa96eac42.png)

added validAudiences with mobile app application id as a valid audience...
![image](https://user-images.githubusercontent.com/3155241/57825520-396b8880-776d-11e9-8cb6-1eefac3b5d36.png)

this works...tbh...not sure why... :)

**Comment by jennyf19** [comment]
Sorry @markti ...missed this...did you get this figured out?

**Comment by jennyf19** [comment]
@markti I"m assuming this has been resolved....if not, please reopen and tag me. thanks.
