### ISSUE TITLE
AuthenticationContinuationHelper does not exist in the current context CS0103

### ISSUE THREAD

**Issue by markti** [Azure-Samples/active-directory-b2c-xamarin-native#79]
Using v2.6.1 of the nuget package. Running on Mac OS X using VS2017 I am trying to debug using an iPhone emulator XR iOS 12.1.

**Comment by jennyf19** [comment]
@markti Can you try with latest version (2.7.1)? or if you want to try our new api, move to [v3](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-3-released). And, if you have time, please give feedback on the new [api here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/933). Thank you.

**Comment by cmw9706** [comment]
I am having the same issue and I am using preview 3.0.0? I am building for android and trying to override my OnActivityResult

Any word on why this is happening?

**Comment by jennyf19** [comment]
@cmw9706 @markti 
MSAL v3.x references MonoAndroid 9 as a target framework. You will need to change the target framework in the Android.csproj file from 8.1 to 9.0
`<TargetFrameworkVersion>v9.0</TargetFrameworkVersion>`
Then, you should be able to reference `AuthenticationContinuationHelper`.
See this [issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/941) for more details.

**Comment by cmw9706** [comment]
Changed to MonoAndroid 9 and it works :)

**Comment by jennyf19** [comment]
@cmw9706 thanks for the quick update. we haven't decided if we should move the target framework back to 8.1 or stay at 9. if you want to give feedback, please do so in the issue I linked above.

**Comment by jennyf19** [comment]
@markti @cmw9706  I think we're sticking w/MonoAndroid 9. going to close this issue.
