### ISSUE TITLE
Log in for iPhone 6s (iOS 10.2) Simulator Log-in Infinite Loop

### ISSUE THREAD

**Issue by jonathanmtg** [Azure-Samples/active-directory-b2c-xamarin-native#8]
When using active-directory-b2c-xamarin-native on an iPhone 6s (iOS 10.2) Simulator, after authenticating I am passed back to the log in screen even though I receive a new IdToken from GetTokenAsync.  This loop appears to be infinite.

**Comment by jonathanmtg** [comment]
It appears the cache is not storing the IUser object after logging in.

**Comment by gsacavdm** [comment]
MSAL for Xamarin has known issues with the iPhone/iOS emulators. In the interim, can you deploy to an iPhone to see if this behavior repro's? It should not be a problem on actual devices.

**Comment by gsacavdm** [comment]
Leaving #7 open in place of this one.
