### ISSUE TITLE
MsalClientException when using custom sign in policy

### ISSUE THREAD

**Issue by onionhammer** [Azure-Samples/active-directory-b2c-xamarin-native#9]
We're using an identity provider with SAML integration with the new MSAL client, when we use the default sign in policy (B2C_1_Default) the authentication token comes back fine, when we use the custom policy (which works fine for the old experimental ADAL library) we get the following error:

```
MsalClientException: client info is null
```

It looks like the response object doesnt include a couple things, causing errors

Response when using the custom policy
```json
{
    "access_token": "...",
    "id_token": "...",
    "token_type": "Bearer",
    "not_before": "1495204421",
    "expires_in": "3600",
    "expires_on": "1495208021",
    "resource": "...",
    "refresh_token": "...",
    "refresh_token_expires_in": "1209600"
}
```

Response when using the default policy
```
{
    "access_token": "...",
    "id_token": "...",
    "token_type": "Bearer",
    "not_before": 1495204558,
    "expires_in": 3600,
    "expires_on": 1495208158,
    "resource": "...",
    "client_info": "...",
    "scope": "... onmicrosoft.com/mobileapi/readwrite",
    "refresh_token": "...",
    "refresh_token_expires_in": 1209600
}
```

As you can see, the default policy is getting back client_info and scope

**Comment by gsacavdm** [comment]
This is a known issue. We're working on getting this fixed.
Adding @parakhj and @rojasja for visibility

**Comment by parakhj** [comment]
@onionhammer Please update your custom policy...

Add the following line:
`<Item Key="SendTokenResponseBodyWithJsonNumbers">true</Item>`
in your 'JwtIssuer' technical profile (it should be in your base file).

Final result:
 
        <TechnicalProfile Id="JwtIssuer">
          <DisplayName>JWT Issuer</DisplayName>
          <Protocol Name="None" />
          <OutputTokenFormat>JWT</OutputTokenFormat>
          <Metadata>
            <Item Key="client_id">{service:te}</Item>
            <Item Key="issuer_refresh_token_user_identity_claim_type">objectId</Item>

            
            <Item Key="SendTokenResponseBodyWithJsonNumbers">true</Item>
             ...
          </Metadata>

**Comment by gsacavdm** [comment]
Starter pack for custom policies has also been updated. Closing this issue.
