### ISSUE TITLE
Office 365 login screen coming up not Azure

### ISSUE THREAD

**Issue by JamesHHoustonII** [Azure-Samples/active-directory-b2c-xamarin-native#91]
In the example it shows the Azure B2C login screen I am getting the Office 365 login not sure why and the example states to use tenantId. Where am I supposed to put the tenantId? Thanks

**Comment by jennyf19** [comment]
@JamesHHoustonII The tenant will go [here](https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/blob/master/UserDetailsClient/UserDetailsClient.Core/Features/LogOn/B2CConstants.cs#L10) in the sample. Did you create a [b2C tenant](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-tenant)?

**Comment by JamesHHoustonII** [comment]
Thank you but I have found azure b2c for uwp and wpf to be a waste of time.
It is apparent that Microsoft wants developers to use ASP and I have no use
for ASP. Thank you for the reply but I have decided it is easier to build a
security suite for signup, login and reset myself then to waste another
minute on the azure b2c solution.

**Comment by jennyf19** [comment]
@JamesHHoustonII Thanks for the feedback, sorry it was not a good experience for you.

FYI - @valnav
