### ISSUE TITLE
Authentication is not working

### ISSUE THREAD

**Issue by subbiahkk** [Azure-Samples/active-directory-b2c-xamarin-native#98]
I have downloaded the MSAL 4.2.1 version and its working with the built in Client id and TenantID. Its also working for my Client/Tenant Ids. But when I create a new Xamarin form App and copy/paste the exact files its struck in the browser. After entering the credentials and clicked the Login button its stayed in the same screen.  
I have override OnActivityResult on MainActivity
Updated Manifestxml with msal<TenantID>://auth
I have copied all the refrences used in ur project.
But its strucked in the Browser, Any other changes i need to do?

**Comment by jennyf19** [comment]
@subbiahkk are you getting any errors or it's just stuck in the browser? Can you get logs or a stack trace?

**Comment by jennyf19** [comment]
@subbiahkk any update on this?

**Comment by jennyf19** [comment]
Closing as no response.

**Comment by nimccoll** [comment]
I am able to reproduce this same issue

**Comment by jennyf19** [comment]
@nimccoll which platform?

**Comment by nimccoll** [comment]
Android 9.0 - API 28. Thanks.

Nick McCollum | Senior Azure FastTrack Engineer | Azure CxP Engineering | Microsoft
Phone: 231-557-9601
Email: nimccoll@microsoft.com<mailto:nimccoll@microsoft.com>
[Certifications7_LG]

**Comment by nimccoll** [comment]
Ok I discovered the issue and this may have been the original poster's issue as well. It turns out I had a malformed DataScheme property in the IntentFilter attribute in my MSALActivity.cs file.

**Comment by jennyf19** [comment]
Thanks for the update @nimccoll ....glad you figured it out. Is there something we can put in our wiki to help other customers, as you're not the first one to hit this issue?
